//=========================
//===== Phoneme Names =====
//=========================

const DICT_NAMES_MALE = [
    {"text":"Aaron", "phonemes":"EH1 R AH0 N"},
    {"text":"Abel", "phonemes":"EY1 B AH0 L"},
    {"text":"Abraham", "phonemes":"EY1 B R AH0 HH AE2 M"},
    {"text":"Adrian", "phonemes":"EY1 D R IY0 AH0 N"},
    {"text":"Aiden", "phonemes":"EY2 D EH1 N"},
    {"text":"Alan", "phonemes":"AE1 L AH0 N"},
    {"text":"Alex", "phonemes":"AE1 L AH0 K S"},
    {"text":"Albert", "phonemes":"AE1 L B ER0 T"},
    {"text":"Alejandro", "phonemes":"AA0 L EY0 Y AA1 N D R OW0"},
    {"text":"Alexander", "phonemes":"AE2 L IH0 G Z AE1 N D ER0"},
    {"text":"Andy", "phonemes":"AE1 N D IY0"},
    {"text":"Andrew", "phonemes":"AE1 N D R UW0"},
    {"text":"Angel", "phonemes":"EY1 N JH AH0 L"},
    {"text":"Anthony", "phonemes":"AE1 N TH AO0 N IY2"},
    {"text":"Ashton", "phonemes":"AE1 SH T AH0 N"},
    {"text":"Austin", "phonemes":"AO1 S T AH0 N"},
    {"text":"Avery", "phonemes":"EY1 V ER0 IY0"},
    {"text":"Axel", "phonemes":"AE1 K S AH0 L"},
    {"text":"Barry", "phonemes":"B AE1 R IY0"},
    {"text":"Bennett", "phonemes":"B EH1 N AH0 T"},
    {"text":"Benjamin", "phonemes":"B EH1 N JH AH0 M AH0 N"},
    {"text":"Blake", "phonemes":"B L EY1 K"},
    {"text":"Bob", "phonemes":"B AA1 B"},
    {"text":"Boris", "phonemes":"B AO1 R IH0 S"},
    {"text":"Brad", "phonemes":"B R AE1 D"},
    {"text":"Bradley", "phonemes":"B R AE1 D L IY0"},
    {"text":"Brady", "phonemes":"B R EY1 D IY0"},
    {"text":"Brandon", "phonemes":"B R AE1 N D AH0 N"},
    {"text":"Brantley", "phonemes":"B R AE1 N T L IY0"},
    {"text":"Braxton", "phonemes":"B R AE1 K S T AH0 N"},
    {"text":"Brayden", "phonemes":"B R EY D EH N"},
    {"text":"Brian", "phonemes":"B R AY AH N"},
    {"text":"Bryce", "phonemes":"B R AY S"},
    {"text":"Caleb", "phonemes":"K EY L AH B"},
    {"text":"Calvin", "phonemes":"K AE L V AH N"},
    {"text":"Cameron", "phonemes":"K AE M ER AH N"},
    {"text":"Carl", "phonemes":"K AA R L"},
    {"text":"Carter", "phonemes":"K AA R T ER"},
    {"text":"Chad", "phonemes":"CH AE D"},
    {"text":"Chase", "phonemes":"CH EY S"},
    {"text":"Chris", "phonemes":"K R IH S"},
    {"text":"Christian", "phonemes":"K R IH S CH AH N"},
    {"text":"Christopher", "phonemes":"K R IH S T AH F ER"},
    {"text":"Clarke", "phonemes":"K L AA R K"},
    {"text":"Cody", "phonemes":"K OW D IY"},
    {"text":"Colin", "phonemes":"K OW L IH N"},
    {"text":"Connor", "phonemes":"K AA N ER"},
    {"text":"Damian", "phonemes":"D EY M IY AH N"},
    {"text":"Dan", "phonemes":"D AE N"},
    {"text":"Daniel", "phonemes":"D AE N Y AH L"},
    {"text":"David", "phonemes":"D EY V IH D"},
    {"text":"Derek", "phonemes":"D EH R IH K"},
    {"text":"Diego", "phonemes":"D IY EY G OW"},
    {"text":"Dominic", "phonemes":"D AA M AH N IH K"},
    {"text":"Dylan", "phonemes":"D IH L AH N"},
    {"text":"Eden", "phonemes":"IY D AH N"},
    {"text":"Edward", "phonemes":"EH D W ER D"},
    {"text":"Emmett", "phonemes":"EH M IH T"},
    {"text":"Elias", "phonemes":"AH L AY AH S"},
    {"text":"Elijah", "phonemes":"EH L AY JH AH"},
    {"text":"Eric", "phonemes":"EH R IH K"},
    {"text":"Ethan", "phonemes":"IY TH AH N"},
    {"text":"Evan", "phonemes":"EH V AH N"},
    {"text":"Ezekiel", "phonemes":"EH Z EH K IY AH L"},
    {"text":"Fred", "phonemes":"F R EH D"},
    {"text":"Gabriel", "phonemes":"G EY B R IY AH L"},
    {"text":"Garrett", "phonemes":"G AE R IH T"},
    {"text":"Gary", "phonemes":"G EH R IY"},
    {"text":"Gavin", "phonemes":"G AE V IH N"},
    {"text":"George", "phonemes":"JH AO R JH"},
    {"text":"Graham", "phonemes":"G R EY AH M"},
    {"text":"Grant", "phonemes":"G R AE N T"},
    {"text":"Gregory", "phonemes":"G R EH G ER IY"},
    {"text":"Harry", "phonemes":"HH EH R IY"},
    {"text":"Harold", "phonemes":"HH EH R AH L D"},
    {"text":"Hector", "phonemes":"HH EH K T ER"},
    {"text":"Henry", "phonemes":"HH EH N R IY"},
    {"text":"Hudson", "phonemes":"HH AH D S AH N"},
    {"text":"Hunter", "phonemes":"HH AH N T ER"},
    {"text":"Ian", "phonemes":"IY AH N"},
    {"text":"Isaac", "phonemes":"AY Z AH K"},
    {"text":"Ivan", "phonemes":"AY V AH N"},
    {"text":"Jack", "phonemes":"JH AE K"},
    {"text":"Jackson", "phonemes":"JH AE K S AH N"},
    {"text":"Jacob", "phonemes":"JH EY K AH B"},
    {"text":"James", "phonemes":"JH EY M Z"},
    {"text":"Jason", "phonemes":"JH EY S AH N"},
    {"text":"Jayden", "phonemes":"JH EY D AH N"},
    {"text":"Jeff", "phonemes":"JH EH F"},
    {"text":"Jeremy", "phonemes":"JH EH R AH M IY"},
    {"text":"Jesse", "phonemes":"JH EH S IY"},
    {"text":"John", "phonemes":"JH AA N"},
    {"text":"Jonah", "phonemes":"JH OW N AH"},
    {"text":"Jonathan", "phonemes":"JH AA N AH TH AH N"},
    {"text":"Jordan", "phonemes":"JH AO R D AH N"},
    {"text":"Joseph", "phonemes":"JH OW S AH F"},
    {"text":"Jose", "phonemes":"HH OW Z EY"},
    {"text":"Joshua", "phonemes":"JH AA SH UW AH"},
    {"text":"Juan", "phonemes":"W AA N"},
    {"text":"Jude", "phonemes":"JH UW D"},
    {"text":"Julian", "phonemes":"JH UW L IY AH N"},
    {"text":"Kenneth", "phonemes":"K EH N IH TH"},
    {"text":"Landon", "phonemes":"L AE N D AH N"},
    {"text":"Leonardo", "phonemes":"L IY AH N AA R D OW"},
    {"text":"Levi", "phonemes":"L IY V AY"},
    {"text":"Liam", "phonemes":"L IY AH M"},
    {"text":"Logan", "phonemes":"L OW G AH N"},
    {"text":"Lucas", "phonemes":"L UW K AH S"},
    {"text":"Luke", "phonemes":"L UW K"},
    {"text":"Malachi", "phonemes":"M AH L AE CH IY"},
    {"text":"Marcus", "phonemes":"M AA R K AH S"},
    {"text":"Mark", "phonemes":"M AA R K"},
    {"text":"Mason", "phonemes":"M EY S AH N"},
    {"text":"Matt", "phonemes":"M AE T"},
    {"text":"Mathias", "phonemes":"M AH TH AY AH S"},
    {"text":"Matthew", "phonemes":"M AE TH Y UW"},
    {"text":"Max", "phonemes":"M AE K S"},
    {"text":"Maxwell", "phonemes":"M AE K S W EH L"},
    {"text":"Mike", "phonemes":"M AY K"},
    {"text":"Michael", "phonemes":"M AY K AH L"},
    {"text":"Miles", "phonemes":"M AY L Z"},
    {"text":"Miguel", "phonemes":"M IH G EH L"},
    {"text":"Mohammad", "phonemes":"M OW HH AA M EH D"},
    {"text":"Nathan", "phonemes":"N EY TH AH N"},
    {"text":"Nathaniel", "phonemes":"N AH TH AE N Y AH L"},
    {"text":"Nicholas", "phonemes":"N IH K AH L AH S"},
    {"text":"Noah", "phonemes":"N OW AH"},
    {"text":"Nolan", "phonemes":"N OW L AH N"},
    {"text":"Omar", "phonemes":"OW M AA R"},
    {"text":"Oscar", "phonemes":"AO S K ER"},
    {"text":"Owen", "phonemes":"OW AH N"},
    {"text":"Patrick", "phonemes":"P AE T R IH K"},
    {"text":"Paul", "phonemes":"P AO L"},
    {"text":"Pete", "phonemes":"P IY T"},
    {"text":"Phillip", "phonemes":"F IH L IH P"},
    {"text":"Phil", "phonemes":"F IH L"},
    {"text":"Preston", "phonemes":"P R EH S T AH N"},
    {"text":"Peyton", "phonemes":"P EY T AH N"},
    {"text":"Raymond", "phonemes":"R EY M AH N D"},
    {"text":"Robert", "phonemes":"R AA B ER T"},
    {"text":"Roman", "phonemes":"R OW M AH N"},
    {"text":"Reginald", "phonemes":"R EH JH AH N AH L D"},
    {"text":"Richard", "phonemes":"R IH CH ER D"},
    {"text":"Roger", "phonemes":"R AA JH ER"},
    {"text":"Roy", "phonemes":"R OY"},
    {"text":"Ryan", "phonemes":"R AY AH N"},
    {"text":"Ryker", "phonemes":"R AY K ER"},
    {"text":"Samuel", "phonemes":"S AE M Y UW L"},
    {"text":"Santiago", "phonemes":"S AE N T IY AA G OW"},
    {"text":"Shane", "phonemes":"SH EY N"},
    {"text":"Simon", "phonemes":"S AY M AH N"},
    {"text":"Steve", "phonemes":"S T IY V"},
    {"text":"Steven", "phonemes":"S T IY V AH N"},
    {"text":"Tanner", "phonemes":"T AE N ER"},
    {"text":"Theodore", "phonemes":"TH IY AH D AO R"},
    {"text":"Timothy", "phonemes":"T IH M AH TH IY"},
    {"text":"Toby", "phonemes":"T OW B IY"},
    {"text":"Tom", "phonemes":"T AA M"},
    {"text":"Tony", "phonemes":"T OW N IY"},
    {"text":"Travis", "phonemes":"T R AE V IH S"},
    {"text":"Tristan", "phonemes":"T R IH S T AE N"},
    {"text":"Tucker", "phonemes":"T AH K ER"},
    {"text":"Tyler", "phonemes":"T AY L ER"},
    {"text":"Victor", "phonemes":"V IH K T ER"},
    {"text":"Vincent", "phonemes":"V IH N S EH N T"},
    {"text":"Weston", "phonemes":"W EH S T AH N"},
    {"text":"Will", "phonemes":"W IH L"},
    {"text":"William", "phonemes":"W IH L Y AH M"},
    {"text":"Wyatt", "phonemes":"W AY AH T"},
    {"text":"Zach", "phonemes":"Z AE K"},
    {"text":"Zachary", "phonemes":"Z AE K ER IY"},
];


const DICT_NAMES_FEMALE = [
    {"text":"Abigail", "phonemes":"AE B AH G EY L"},
    {"text":"Adalyn", "phonemes":"AE D AH L AH N"},
    {"text":"Addison", "phonemes":"AE D IH S AH N"},
    {"text":"Adriana", "phonemes":"EY D R IY AE N AH"},
    {"text":"Alana", "phonemes":"AA L AE N AH"},
    {"text":"Alexis", "phonemes":"AH L EH K S IH S"},
    {"text":"Alice", "phonemes":"AE L IH S"},
    {"text":"Alivia", "phonemes":"AH L IH V IY AH"},
    {"text":"Allison", "phonemes":"AE L IH S AH N"},
    {"text":"Alexa", "phonemes":"AH L EH K S AH"},
    {"text":"Alexandria", "phonemes":"AE L AH G Z AE N D R IY AH"},
    {"text":"Alyssa", "phonemes":"AH L IH S AH"},
    {"text":"Amelia", "phonemes":"AH M IY L Y AH"},
    {"text":"Amy", "phonemes":"EY M IY"},
    {"text":"Andrea", "phonemes":"AE N D R IY AH"},
    {"text":"Angela", "phonemes":"AE N JH AH L AH"},
    {"text":"Angelina", "phonemes":"AE N JH EH L IY N AH"},
    {"text":"Anna", "phonemes":"AE N AH"},
    {"text":"Annabelle", "phonemes":"AE N AH B AH L"},
    {"text":"Annie", "phonemes":"AE N IY"},
    {"text":"Arabella", "phonemes":"AE R AH B EH L AH"},
    {"text":"Ariana", "phonemes":"AA R IY AE N AH"},
    {"text":"Ariel", "phonemes":"EH R IY AH L"},
    {"text":"Ashley", "phonemes":"AE SH L IY"},
    {"text":"Athena", "phonemes":"AE TH IY N AH"},
    {"text":"Aubrey", "phonemes":"AO B R IY"},
    {"text":"Audrey", "phonemes":"AO D R IY"},
    {"text":"Aurora", "phonemes":"ER AO R AH"},
    {"text":"Ava", "phonemes":"EY V AH"},
    {"text":"Bella", "phonemes":"B EH L AH"},
    {"text":"Beth", "phonemes":"B EH TH"},
    {"text":"Bonnie", "phonemes":"B AA N IY"},
    {"text":"Brianna", "phonemes":"B R IY AE N AH"},
    {"text":"Brooklyn", "phonemes":"B R UH K L AH N"},
    {"text":"Camila", "phonemes":"K AE M AH L AH"},
    {"text":"Camille", "phonemes":"K AH M IY L"},
    {"text":"Carla", "phonemes":"K AA R L AA"},
    {"text":"Caroline", "phonemes":"K EH R AH L AY N"},
    {"text":"Cassie", "phonemes":"K AE S IY"},
    {"text":"Catherine", "phonemes":"K AE TH ER IH N"},
    {"text":"Cecilia", "phonemes":"S IH S IY L Y AH"},
    {"text":"Charity", "phonemes":"CH EH R IH T IY"},
    {"text":"Charlotte", "phonemes":"SH AA R L AH T"},
    {"text":"Chelsea", "phonemes":"CH EH L S IY"},
    {"text":"Chloe", "phonemes":"K L OW IY"},
    {"text":"Christiana", "phonemes":"K R IH S T IY AE N AH"},
    {"text":"Claire", "phonemes":"K L EH R"},
    {"text":"Clara", "phonemes":"K L AE R AH"},
    {"text":"Cora", "phonemes":"K AO R AH"},
    {"text":"Danielle", "phonemes":"D AE N IY EH L"},
    {"text":"Daisy", "phonemes":"D EY Z IY"},
    {"text":"Diane", "phonemes":"D AY AE N"},
    {"text":"Dolly", "phonemes":"D AA L IY"},
    {"text":"Doris", "phonemes":"D AO R AH S"},
    {"text":"Elizabeth", "phonemes":"IH L IH Z AH B AH TH"},
    {"text":"Eleanor", "phonemes":"EH L AH N AO R"},
    {"text":"Elise", "phonemes":"AH L IY S"},
    {"text":"Ella", "phonemes":"EH L AH"},
    {"text":"Eliza", "phonemes":"IH L AY Z AH"},
    {"text":"Emily", "phonemes":"EH M IH L IY"},
    {"text":"Emma", "phonemes":"EH M AH"},
    {"text":"Esther", "phonemes":"EH S T ER"},
    {"text":"Ethel", "phonemes":"EH TH AH L"},
    {"text":"Eva", "phonemes":"EY V AH"},
    {"text":"Evelyn", "phonemes":"EH V AH L AH N"},
    {"text":"Faith", "phonemes":"F EY TH"},
    {"text":"Felicity", "phonemes":"F IH L IH S AH T IY"},
    {"text":"Fiona", "phonemes":"F IY OW N AH"},
    {"text":"Flora", "phonemes":"F L AO R AH"},
    {"text":"Gabriella", "phonemes":"G AA B R IY EH L AA"},
    {"text":"Genesis", "phonemes":"JH EH N AH S AH S"},
    {"text":"Genevieve", "phonemes":"JH EH N AH V IY V"},
    {"text":"Georgina", "phonemes":"JH AO R JH IY N AH"},
    {"text":"Gianna", "phonemes":"JH AY AE N AH"},
    {"text":"Giselle", "phonemes":"ZH IH S EH L"},
    {"text":"Grace", "phonemes":"G R EY S"},
    {"text":"Hailey", "phonemes":"HH EY L IY"},
    {"text":"Hannah", "phonemes":"HH AE N AH"},
    {"text":"Harmony", "phonemes":"HH AA R M AH N IY"},
    {"text":"Harriet", "phonemes":"HH EH R IY AH T"},
    {"text":"Hazel", "phonemes":"HH EY Z AH L"},
    {"text":"Heather", "phonemes":"HH EH DH ER"},
    {"text":"Helen", "phonemes":"HH EH L AH N"},
    {"text":"Hope", "phonemes":"HH OW P"},
    {"text":"Isabella", "phonemes":"IH Z AH B EH L AH"},
    {"text":"Ivy", "phonemes":"AY V IY"},
    {"text":"Jasmine", "phonemes":"JH AE Z M AH N"},
    {"text":"Jacqueline", "phonemes":"JH AE K W AH L IH N"},
    {"text":"Jayla", "phonemes":"JH EY L AH"},
    {"text":"Jennifer", "phonemes":"JH EH N AH F ER"},
    {"text":"Jessica", "phonemes":"JH EH S IH K AH"},
    {"text":"Jocelyn", "phonemes":"JH AO S L IH N"},
    {"text":"Jody", "phonemes":"JH OW D IY"},
    {"text":"Josephine", "phonemes":"JH OW S AH F IY N"},
    {"text":"Julia", "phonemes":"JH UW L Y AH"},
    {"text":"Juliana", "phonemes":"JH UW L IY AE N AH"},
    {"text":"Kaitlyn", "phonemes":"K EY T L AH N"},
    {"text":"Kate", "phonemes":"K EY T"},
    {"text":"Katie", "phonemes":"K EY T IY"},
    {"text":"Katy", "phonemes":"K EY T IY"},
    {"text":"Kathy", "phonemes":"K AE TH IY"},
    {"text":"Kaylee", "phonemes":"K EY L IY IY"},
    {"text":"Kimberly", "phonemes":"K IH M B ER L IY"},
    {"text":"Laila", "phonemes":"L EY L AH"},
    {"text":"Laura", "phonemes":"L AO R AH"},
    {"text":"Lauren", "phonemes":"L AO R AH N"},
    {"text":"Layla", "phonemes":"L EY L AA"},
    {"text":"Leah", "phonemes":"L IY AH"},
    {"text":"Leilani", "phonemes":"L AH L AA N IY"},
    {"text":"Lillian", "phonemes":"L IH L IY AH N"},
    {"text":"Lily", "phonemes":"L IH L IY"},
    {"text":"Lola", "phonemes":"L OW L AH"},
    {"text":"Lucia", "phonemes":"L UW SH AH"},
    {"text":"Lucy", "phonemes":"L UW S IY"},
    {"text":"Lydia", "phonemes":"L IH D IY AH"},
    {"text":"Madeline", "phonemes":"M AE D AH L IH N"},
    {"text":"Madison", "phonemes":"M AE D AH S AH N"},
    {"text":"Maggie", "phonemes":"M AE G IY"},
    {"text":"Maria", "phonemes":"M ER IY AH"},
    {"text":"Marion", "phonemes":"M EH R IY AH N"},
    {"text":"Mary", "phonemes":"M EH R IY"},
    {"text":"Margaret", "phonemes":"M AA R G ER IH T"},
    {"text":"Mavis", "phonemes":"M EY V IH S"},
    {"text":"Maud", "phonemes":"M AO D"},
    {"text":"Maureen", "phonemes":"M AO R IY N"},
    {"text":"Megan", "phonemes":"M EY G AH N"},
    {"text":"Melanie", "phonemes":"M EH L AH N IY"},
    {"text":"Melissa", "phonemes":"M AH L IH S AH"},
    {"text":"Melody", "phonemes":"M EH L AH D IY"},
    {"text":"Mia", "phonemes":"M IY AH"},
    {"text":"Michelle", "phonemes":"M IH SH EH L"},
    {"text":"Mildred", "phonemes":"M IH L D R IH D"},
    {"text":"Miranda", "phonemes":"M ER AE N D AH"},
    {"text":"Molly", "phonemes":"M AA L IY"},
    {"text":"Natalie", "phonemes":"N AE T AH L IY"},
    {"text":"Naomi", "phonemes":"N EY OW M IY"},
    {"text":"Nadine", "phonemes":"N AH D IY N"},
    {"text":"Nicole", "phonemes":"N IH K OW L"},
    {"text":"Nora", "phonemes":"N AO R AH"},
    {"text":"Ocean", "phonemes":"OW SH AH N"},
    {"text":"Olivia", "phonemes":"OW L IH V IY AH"},
    {"text":"Paige", "phonemes":"P EY JH"},
    {"text":"Paisley", "phonemes":"P EY Z L IY"},
    {"text":"Penelope", "phonemes":"P AH N EH L AH P IY"},
    {"text":"Polly", "phonemes":"P AA L IY"},
    {"text":"Rachel", "phonemes":"R EY CH AH L"},
    {"text":"Rebecca", "phonemes":"R AH B EH K AH"},
    {"text":"Rhiannon", "phonemes":"R AY AE N AH N"},
    {"text":"Riley", "phonemes":"R AY L IY"},
    {"text":"Ruby", "phonemes":"R UW B IY"},
    {"text":"Ruth", "phonemes":"R UW TH"},
    {"text":"Sadie", "phonemes":"S AE D IY"},
    {"text":"Sally", "phonemes":"S AE L IY"},
    {"text":"Samantha", "phonemes":"S AH M AE N TH AH"},
    {"text":"Sarah", "phonemes":"S EH R AH"},
    {"text":"Savannah", "phonemes":"S AH V AE N AH"},
    {"text":"Scarlett", "phonemes":"S K AA R L IH T"},
    {"text":"Serenity", "phonemes":"S ER EH N AH T IY"},
    {"text":"Sharon", "phonemes":"SH AE R AH N"},
    {"text":"Sienna", "phonemes":"S IY EH N AH"},
    {"text":"Sofia", "phonemes":"S OW F IY AH"},
    {"text":"Sonya", "phonemes":"S OW N Y AH"},
    {"text":"Sophia", "phonemes":"S OW F IY AH"},
    {"text":"Stella", "phonemes":"S T EH L AH"},
    {"text":"Stephanie", "phonemes":"S T EH F AH N IY"},
    {"text":"Susan", "phonemes":"S UW Z AH N"},
    {"text":"Suzanne", "phonemes":"S UW Z AE N"},
    {"text":"Taylor", "phonemes":"T EY L ER"},
    {"text":"Tiffany", "phonemes":"T IH F AH N IY"},
    {"text":"Trinity", "phonemes":"T R IH N AH T IY"},
    {"text":"Una", "phonemes":"UW N AH"},
    {"text":"Valerie", "phonemes":"V AE L ER IY"},
    {"text":"Vanessa", "phonemes":"V AH N EH S AH"},
    {"text":"Victoria", "phonemes":"V IH K T AO R IY AH"},
    {"text":"Virginia", "phonemes":"V ER JH IH N Y AH"},
    {"text":"Violet", "phonemes":"V AY AH L IH T"},
    {"text":"Vivian", "phonemes":"V IH V IY AH N"},
    {"text":"Zoe", "phonemes":"Z OW IY"},
];
