//=========================
//===== Phoneme Names =====
//=========================

// lists derived from: http://www.ashley-bovan.co.uk/words/partsofspeech.html

const DICT_NOUNS = [
    {"text":"Aaron", "phonenes":"EH1 R AH0 N"},
    {"text":"aardvark", "phonemes":"AA R D V AA R K"},
    {"text":"accordion", "phonemes":"AH K AO R D IY AH N"},
    {"text":"account", "phonemes":"AH K AW N T"},
    {"text":"airplane", "phonemes":"EH R P L EY N"},
    {"text":"albatross", "phonemes":"AE L B AH T R AA S"},
    {"text":"alcohol", "phonemes":"AE L K AH HH AA L"},
    {"text":"alligator", "phonemes":"AE L AH G EY T ER"},
    {"text":"ambulance", "phonemes":"AE M B Y AH L AH N S"},
    {"text":"animal", "phonemes":"AE N AH M AH L"},
    {"text":"anteater", "phonemes":"AE N T IY T ER"},
    {"text":"antelope", "phonemes":"AE N T AH L OW P"},
    {"text":"arm", "phonemes":"AA R M"},
    {"text":"armadillo", "phonemes":"AA R M AH D IH L OW"},
    {"text":"armchair", "phonemes":"AA R M CH EH R"},
    {"text":"asparagus", "phonemes":"AH S P EH R AH G AH S"},
    {"text":"atom", "phonemes":"AE T AH M"},
    {"text":"author", "phonemes":"AO TH ER"},
    {"text":"baboon", "phonemes":"B AH B UW N"},
    {"text":"baby", "phonemes":"B EY B IY"},
    {"text":"bacon", "phonemes":"B EY K AH N"},
    {"text":"badge", "phonemes":"B AE JH"},
    {"text":"badger", "phonemes":"B AE JH ER"},
    {"text":"bagel", "phonemes":"B EY G AH L"},
    {"text":"bagpipe", "phonemes":"B AE G P AY P"},
    {"text":"balloon", "phonemes":"B AH L UW N"},
    {"text":"bamboo", "phonemes":"B AE M B UW"},
    {"text":"banana", "phonemes":"B AH N AE N AH"},
    {"text":"band", "phonemes":"B AE N D"},
    {"text":"bandana", "phonemes":"B AE N D AE N AH"},
    {"text":"bangle", "phonemes":"B AE NG G AH L"},
    {"text":"banjo", "phonemes":"B AE N JH OW"},
    {"text":"bank", "phonemes":"B AE NG K"},
    {"text":"baseball", "phonemes":"B EY S B AO L"},
    {"text":"basketball", "phonemes":"B AE S K AH T B AO L"},
    {"text":"bassoon", "phonemes":"B AH S UW N"},
    {"text":"bat", "phonemes":"B AE T"},
    {"text":"bathtub", "phonemes":"B AE TH T AH B"},
    {"text":"battery", "phonemes":"B AE T ER IY"},
    {"text":"bead", "phonemes":"B IY D"},
    {"text":"bean", "phonemes":"B IY N"},
    {"text":"bear", "phonemes":"B EH R"},
    {"text":"beard", "phonemes":"B IH R D"},
    {"text":"beast", "phonemes":"B IY S T"},
    {"text":"beautician", "phonemes":"B Y UW T IH SH AH N"},
    {"text":"beauty", "phonemes":"B Y UW T IY"},
    {"text":"beaver", "phonemes":"B IY V ER"},
    {"text":"bed", "phonemes":"B EH D"},
    {"text":"bee", "phonemes":"B IY"},
    {"text":"beer", "phonemes":"B IH R"},
    {"text":"beetle", "phonemes":"B IY T AH L"},
    {"text":"beggar", "phonemes":"B EH G ER"},
    {"text":"berry", "phonemes":"B EH R IY"},
    {"text":"bicycle", "phonemes":"B AY S IH K AH L"},
    {"text":"bird", "phonemes":"B ER D"},
    {"text":"boat", "phonemes":"B OW T"},
    {"text":"bomb", "phonemes":"B AA M"},
    {"text":"book", "phonemes":"B UH K"},
    {"text":"boot", "phonemes":"B UW T"},
    {"text":"bottle", "phonemes":"B AA T AH L"},
    {"text":"bowl", "phonemes":"B OW L"},
    {"text":"box", "phonemes":"B AA K S"},
    {"text":"bra", "phonemes":"B R AA"},
    {"text":"bracket", "phonemes":"B R AE K IH T"},
    {"text":"brain", "phonemes":"B R EY N"},
    {"text":"brass", "phonemes":"B R AE S"},
    {"text":"bread", "phonemes":"B R EH D"},
    {"text":"brick", "phonemes":"B R IH K"},
    {"text":"bucket", "phonemes":"B AH K IH T"},
    {"text":"cabbage", "phonemes":"K AE B AH JH"},
    {"text":"cactus", "phonemes":"K AE K T AH S"},
    {"text":"cake", "phonemes":"K EY K"},
    {"text":"carrot", "phonemes":"K AE R AH T"},
    {"text":"cat", "phonemes":"K AE T"},
    {"text":"cathedral", "phonemes":"K AH TH IY D R AH L"},
    {"text":"chain", "phonemes":"CH EY N"},
    {"text":"chair", "phonemes":"CH EH R"},
    {"text":"chalk", "phonemes":"CH AA K"},
    {"text":"chauffeur", "phonemes":"SH OW F ER"},
    {"text":"cheese", "phonemes":"CH IY Z"},
    {"text":"cheetah", "phonemes":"CH IY T AH"},
    {"text":"chef", "phonemes":"SH EH F"},
    {"text":"cherry", "phonemes":"CH EH R IY"},
    {"text":"chicken", "phonemes":"CH IH K AH N"},
    {"text":"chief", "phonemes":"CH IY F"},
    {"text":"child", "phonemes":"CH AY L D"},
    {"text":"chimpanzee", "phonemes":"CH IH M P AE N Z IY"},
    {"text":"church", "phonemes":"CH ER CH"},
    {"text":"clam", "phonemes":"K L AE M"},
    {"text":"computer", "phonemes":"K AH M P Y UW T ER"},
    {"text":"cow", "phonemes":"K AW"},
    {"text":"cowbell", "phonemes":"K AW B EH L"},
    {"text":"crab", "phonemes":"K R AE B"},
    {"text":"crawdad", "phonemes":"K R AO D AH D"},
    {"text":"crayfish", "phonemes":"K R EY F IH SH"},
    {"text":"crayon", "phonemes":"K R EY AA N"},
    {"text":"cricket", "phonemes":"K R IH K IH T"},
    {"text":"crocodile", "phonemes":"K R AA K AH D AY L"},
    {"text":"croissant", "phonemes":"K W AA S AA N T"},
    {"text":"crown", "phonemes":"K R AW N"},
    {"text":"cucumber", "phonemes":"K Y UW K AH M B ER"},
    {"text":"cup", "phonemes":"K AH P"},
    {"text":"cupcake", "phonemes":"K AH P K EY K"},
    {"text":"daughter", "phonemes":"D AO T ER"},
    {"text":"dentist", "phonemes":"D EH N T AH S T"},
    {"text":"dessert", "phonemes":"D IH Z ER T"},
    {"text":"diamond", "phonemes":"D AY M AH N D"},
    {"text":"dictionary", "phonemes":"D IH K SH AH N EH R IY"},
    {"text":"dinosaur", "phonemes":"D AY N AH S AO R"},
    {"text":"disease", "phonemes":"D IH Z IY Z"},
    {"text":"doctor", "phonemes":"D AA K T ER"},
    {"text":"dog", "phonemes":"D AO G"},
    {"text":"dogsled", "phonemes":"D AO G S L EH D"},
    {"text":"doll", "phonemes":"D AA L"},
    {"text":"dollar", "phonemes":"D AA L ER"},
    {"text":"dolphin", "phonemes":"D AA L F AH N"},
    {"text":"donkey", "phonemes":"D AA NG K IY"},
    {"text":"dragon", "phonemes":"D R AE G AH N"},
    {"text":"dragonfly", "phonemes":"D R AE G AH N F L AY"},
    {"text":"dream", "phonemes":"D R IY M"},
    {"text":"dress", "phonemes":"D R EH S"},
    {"text":"drug", "phonemes":"D R AH G"},
    {"text":"drum", "phonemes":"D R AH M"},
    {"text":"duck", "phonemes":"D AH K"},
    {"text":"eagle", "phonemes":"IY G AH L"},
    {"text":"eel", "phonemes":"IY L"},
    {"text":"egg", "phonemes":"EH G"},
    {"text":"eggplant", "phonemes":"EH G P L AE N T"},
    {"text":"elephant", "phonemes":"EH L AH F AH N T"},
    {"text":"ex", "phonemes":"-HUSBAND	EH K S HH AH Z B AH N D"},
    {"text":"ex", "phonemes":"-WIFE	EH K S W AY F"},
    {"text":"eye", "phonemes":"AY"},
    {"text":"farmer", "phonemes":"F AA R M ER"},
    {"text":"father", "phonemes":"F AA DH ER"},
    {"text":"father", "phonemes":"-IN-LAW	F AA DH ER IH N L AO"},
    {"text":"faucet", "phonemes":"F AO S AH T"},
    {"text":"feather", "phonemes":"F EH DH ER"},
    {"text":"female", "phonemes":"F IY M EY L"},
    {"text":"fireplace", "phonemes":"F AY ER P L EY S"},
    {"text":"fish", "phonemes":"F IH SH"},
    {"text":"flag", "phonemes":"F L AE G"},
    {"text":"flame", "phonemes":"F L EY M"},
    {"text":"flare", "phonemes":"F L EH R"},
    {"text":"floor", "phonemes":"F L AO R"},
    {"text":"flower", "phonemes":"F L AW ER"},
    {"text":"flugelhorn", "phonemes":"F L UW JH EH L HH AO R N"},
    {"text":"flute", "phonemes":"F L UW T"},
    {"text":"fly", "phonemes":"F L AY"},
    {"text":"foam", "phonemes":"F OW M"},
    {"text":"fog", "phonemes":"F AA G"},
    {"text":"fox", "phonemes":"F AA K S"},
    {"text":"fragrance", "phonemes":"F R EY G R AH N S"},
    {"text":"frame", "phonemes":"F R EY M"},
    {"text":"freckle", "phonemes":"F R EH K AH L"},
    {"text":"freezer", "phonemes":"F R IY Z ER"},
    {"text":"freighter", "phonemes":"F R EY T ER"},
    {"text":"fridge", "phonemes":"F R IH JH"},
    {"text":"friend", "phonemes":"F R EH N D"},
    {"text":"frog", "phonemes":"F R AA G"},
    {"text":"frost", "phonemes":"F R AO S T"},
    {"text":"fruit", "phonemes":"F R UW T"},
    {"text":"fuel", "phonemes":"F Y UW AH L"},
    {"text":"fur", "phonemes":"F ER"},
    {"text":"furniture", "phonemes":"F ER N IH CH ER"},
    {"text":"galley", "phonemes":"G AE L IY"},
    {"text":"game", "phonemes":"G EY M"},
    {"text":"gander", "phonemes":"G AE N D ER"},
    {"text":"garage", "phonemes":"G ER AA ZH"},
    {"text":"garden", "phonemes":"G AA R D AH N"},
    {"text":"garlic", "phonemes":"G AA R L IH K"},
    {"text":"gas", "phonemes":"G AE S"},
    {"text":"gasoline", "phonemes":"G AE S AH L IY N"},
    {"text":"gate", "phonemes":"G EY T"},
    {"text":"gateway", "phonemes":"G EY T W EY"},
    {"text":"gauge", "phonemes":"G EY JH"},
    {"text":"gazelle", "phonemes":"G AH Z EH L"},
    {"text":"gear", "phonemes":"G IH R"},
    {"text":"geese", "phonemes":"G IY S"},
    {"text":"ghost", "phonemes":"G OW S T"},
    {"text":"giant", "phonemes":"JH AY AH N T"},
    {"text":"giraffe", "phonemes":"JH ER AE F"},
    {"text":"glass", "phonemes":"G L AE S"},
    {"text":"glove", "phonemes":"G L AH V"},
    {"text":"glue", "phonemes":"G L UW"},
    {"text":"goal", "phonemes":"G OW L"},
    {"text":"goat", "phonemes":"G OW T"},
    {"text":"gold", "phonemes":"G OW L D"},
    {"text":"goldfish", "phonemes":"G OW L D F IH SH"},
    {"text":"golf", "phonemes":"G AA L F"},
    {"text":"gondola", "phonemes":"G AA N D AH L AH"},
    {"text":"gong", "phonemes":"G AO NG"},
    {"text":"goose", "phonemes":"G UW S"},
    {"text":"gorilla", "phonemes":"G ER IH L AH"},
    {"text":"gosling", "phonemes":"G OW S L IH NG"},
    {"text":"governor", "phonemes":"G AH V ER N ER"},
    {"text":"grade", "phonemes":"G R EY D"},
    {"text":"grain", "phonemes":"G R EY N"},
    {"text":"granddaughter", "phonemes":"G R AE N D AO T ER"},
    {"text":"grandfather", "phonemes":"G R AE N D F AA DH ER"},
    {"text":"grandmother", "phonemes":"G R AE N D M AH DH ER"},
    {"text":"grandson", "phonemes":"G R AE N D S AH N"},
    {"text":"grape", "phonemes":"G R EY P"},
    {"text":"grasshopper", "phonemes":"G R AE S HH AA P ER"},
    {"text":"grease", "phonemes":"G R IY S"},
    {"text":"great", "phonemes":"-GRANDFATHER	G R EY T G R AE N D F AA DH ER"},
    {"text":"great", "phonemes":"-GRANDMOTHER	G R EY T G R AE N D M AH TH ER"},
    {"text":"grenade", "phonemes":"G R AH N EY D"},
    {"text":"grill", "phonemes":"G R IH L"},
    {"text":"grip", "phonemes":"G R IH P"},
    {"text":"ground", "phonemes":"G R AW N D"},
    {"text":"guitar", "phonemes":"G IH T AA R"},
    {"text":"gum", "phonemes":"G AH M"},
    {"text":"gun", "phonemes":"G AH N"},
    {"text":"gymnast", "phonemes":"JH IH M N AH S T"},
    {"text":"hacksaw", "phonemes":"HH AE K S AO"},
    {"text":"hail", "phonemes":"HH EY L"},
    {"text":"hair", "phonemes":"HH EH R"},
    {"text":"haircut", "phonemes":"HH EH R K AH T"},
    {"text":"half", "phonemes":"-BROTHER	HH AE F B R AH DH ER"},
    {"text":"half", "phonemes":"-SISTER	HH AE F S IH S T ER"},
    {"text":"halibut", "phonemes":"HH AE L AH B AH T"},
    {"text":"hamburger", "phonemes":"HH AE M B ER G ER"},
    {"text":"hammer", "phonemes":"HH AE M ER"},
    {"text":"hamster", "phonemes":"HH AE M S T ER"},
    {"text":"hand", "phonemes":"HH AE N D"},
    {"text":"handball", "phonemes":"HH AE N D B AO L"},
    {"text":"handsaw", "phonemes":"HH AE N D S AO"},
    {"text":"harbor", "phonemes":"HH AA R B ER"},
    {"text":"hardcover", "phonemes":"HH AA R D K AH V ER"},
    {"text":"hardhat", "phonemes":"HH AA R D HH AE T"},
    {"text":"hardware", "phonemes":"HH AA R D W EH R"},
    {"text":"harmonica", "phonemes":"HH AA R M AA N IH K AH"},
    {"text":"harmony", "phonemes":"HH AA R M AH N IY"},
    {"text":"harp", "phonemes":"HH AA R P"},
    {"text":"hat", "phonemes":"HH AE T"},
    {"text":"hawk", "phonemes":"HH AO K"},
    {"text":"head", "phonemes":"HH EH D"},
    {"text":"headlight", "phonemes":"HH EH D L AY T"},
    {"text":"headline", "phonemes":"HH EH D L AY N"},
    {"text":"health", "phonemes":"HH EH L TH"},
    {"text":"hearing", "phonemes":"HH IY R IH NG"},
    {"text":"heart", "phonemes":"HH AA R T"},
    {"text":"heaven", "phonemes":"HH EH V AH N"},
    {"text":"hedge", "phonemes":"HH EH JH"},
    {"text":"height", "phonemes":"HH AY T"},
    {"text":"helicopter", "phonemes":"HH EH L IH K AA P T ER"},
    {"text":"helmet", "phonemes":"HH EH L M AH T"},
    {"text":"help", "phonemes":"HH EH L P"},
    {"text":"hemp", "phonemes":"HH EH M P"},
    {"text":"hen", "phonemes":"HH EH N"},
    {"text":"herring", "phonemes":"HH EH R IH NG"},
    {"text":"hexagon", "phonemes":"HH EH K S AH G AA N"},
    {"text":"hill", "phonemes":"HH IH L"},
    {"text":"hip", "phonemes":"HH IH P"},
    {"text":"hippopotamus", "phonemes":"HH IH P AH P AA T AH M AH S"},
    {"text":"history", "phonemes":"HH IH S T ER IY"},
    {"text":"hockey", "phonemes":"HH AA K IY"},
    {"text":"hoe", "phonemes":"HH OW"},
    {"text":"hole", "phonemes":"HH OW L"},
    {"text":"holiday", "phonemes":"HH AA L AH D EY"},
    {"text":"home", "phonemes":"HH OW M"},
    {"text":"honey", "phonemes":"HH AH N IY"},
    {"text":"hood", "phonemes":"HH UH D"},
    {"text":"hook", "phonemes":"HH UH K"},
    {"text":"hope", "phonemes":"HH OW P"},
    {"text":"horn", "phonemes":"HH AO R N"},
    {"text":"horse", "phonemes":"HH AO R S"},
    {"text":"hose", "phonemes":"HH OW Z"},
    {"text":"hospital", "phonemes":"HH AA S P IH T AH L"},
    {"text":"hourglass", "phonemes":"AW ER G L AE S"},
    {"text":"house", "phonemes":"HH AW S"},
    {"text":"hovercraft", "phonemes":"HH AH V ER K R AE F T"},
    {"text":"hub", "phonemes":"HH AH B"},
    {"text":"hubcap", "phonemes":"HH AH B K AE P"},
    {"text":"humidity", "phonemes":"HH Y UW M IH D AH T IY"},
    {"text":"hurricane", "phonemes":"HH ER AH K EY N"},
    {"text":"hyacinth", "phonemes":"HH AY AH S IH N TH"},
    {"text":"hydrant", "phonemes":"HH AY D R AH N T"},
    {"text":"hyena", "phonemes":"HH AY IY N AH"},
    {"text":"hygienic", "phonemes":"HH AY JH IY N IH K"},
    {"text":"ice", "phonemes":"AY S"},
    {"text":"icebreaker", "phonemes":"AY S B R EY K ER"},
    {"text":"icicle", "phonemes":"AY S IH K AH L"},
    {"text":"icon", "phonemes":"AY K AA N"},
    {"text":"illegal", "phonemes":"IH L IY G AH L"},
    {"text":"imprisonment", "phonemes":"IH M P R IH Z AH N M AH N T"},
    {"text":"improvement", "phonemes":"IH M P R UW V M AH N T"},
    {"text":"impulse", "phonemes":"IH M P AH L S"},
    {"text":"inch", "phonemes":"IH N CH"},
    {"text":"income", "phonemes":"IH N K AH M"},
    {"text":"industry", "phonemes":"IH N D AH S T R IY"},
    {"text":"ink", "phonemes":"IH NG K"},
    {"text":"innocent", "phonemes":"IH N AH S AH N T"},
    {"text":"input", "phonemes":"IH N P UH T"},
    {"text":"insect", "phonemes":"IH N S EH K T"},
    {"text":"instruction", "phonemes":"IH N S T R AH K SH AH N"},
    {"text":"instrument", "phonemes":"IH N S T R AH M AH N T"},
    {"text":"insulation", "phonemes":"IH N S AH L EY SH AH N"},
    {"text":"insurance", "phonemes":"IH N SH UH R AH N S"},
    {"text":"interactive", "phonemes":"IH N T ER AE K T IH V"},
    {"text":"interest", "phonemes":"IH N T AH R EH S T"},
    {"text":"internet", "phonemes":"IH N T ER N EH T"},
    {"text":"interviewer", "phonemes":"IH N T ER V Y UW ER"},
    {"text":"intestine", "phonemes":"IH N T EH S T AH N"},
    {"text":"invention", "phonemes":"IH N V EH N SH AH N"},
    {"text":"iron", "phonemes":"AY ER N"},
    {"text":"island", "phonemes":"AY L AH N D"},
    {"text":"jacket", "phonemes":"JH AE K AH T"},
    {"text":"jaguar", "phonemes":"JH AE G W AA R"},
    {"text":"jail", "phonemes":"JH EY L"},
    {"text":"jam", "phonemes":"JH AE M"},
    {"text":"james", "phonemes":"JH EY M Z"},
    {"text":"january", "phonemes":"JH AE N Y UW EH R IY"},
    {"text":"jar", "phonemes":"JH AA R"},
    {"text":"jasmine", "phonemes":"JH AE Z M AH N"},
    {"text":"jaw", "phonemes":"JH AO"},
    {"text":"jeep", "phonemes":"JH IY P"},
    {"text":"jelly", "phonemes":"JH EH L IY"},
    {"text":"jellyfish", "phonemes":"JH EH L IY F IH SH"},
    {"text":"jet", "phonemes":"JH EH T"},
    {"text":"jewel", "phonemes":"JH UW AH L"},
    {"text":"join", "phonemes":"JH OY N"},
    {"text":"joke", "phonemes":"JH OW K"},
    {"text":"joseph", "phonemes":"JH OW S AH F"},
    {"text":"journey", "phonemes":"JH ER N IY"},
    {"text":"judge", "phonemes":"JH AH JH"},
    {"text":"judo", "phonemes":"JH UW D OW"},
    {"text":"juice", "phonemes":"JH UW S"},
    {"text":"july", "phonemes":"JH UW L AY"},
    {"text":"jumbo", "phonemes":"JH AH M B OW"},
    {"text":"jump", "phonemes":"JH AH M P"},
    {"text":"jumper", "phonemes":"JH AH M P ER"},
    {"text":"jury", "phonemes":"JH UH R IY"},
    {"text":"justice", "phonemes":"JH AH S T AH S"},
    {"text":"jute", "phonemes":"JH UW T"},
    {"text":"kale", "phonemes":"K EY L"},
    {"text":"kamikaze", "phonemes":"K AA M AH K AA Z IY"},
    {"text":"kangaroo", "phonemes":"K AE NG G ER UW"},
    {"text":"karate", "phonemes":"K ER AA T IY"},
    {"text":"kayak", "phonemes":"K AY AE K"},
    {"text":"ketchup", "phonemes":"K EH CH AH P"},
    {"text":"kettle", "phonemes":"K EH T AH L"},
    {"text":"kettledrum", "phonemes":"K EH T AH L D R AH M"},
    {"text":"key", "phonemes":"K IY"},
    {"text":"keyboard", "phonemes":"K IY B AO R D"},
    {"text":"kick", "phonemes":"K IH K"},
    {"text":"kidney", "phonemes":"K IH D N IY"},
    {"text":"kiss", "phonemes":"K IH S"},
    {"text":"kitchen", "phonemes":"K IH CH AH N"},
    {"text":"kite", "phonemes":"K AY T"},
    {"text":"kitten", "phonemes":"K IH T AH N"},
    {"text":"kitty", "phonemes":"K IH T IY"},
    {"text":"knee", "phonemes":"N IY"},
    {"text":"knife", "phonemes":"N AY F"},
    {"text":"knight", "phonemes":"N AY T"},
    {"text":"knot", "phonemes":"N AA T"},
    {"text":"laborer", "phonemes":"L EY B ER ER"},
    {"text":"lace", "phonemes":"L EY S"},
    {"text":"ladybug", "phonemes":"L EY D IY B AH G"},
    {"text":"lake", "phonemes":"L EY K"},
    {"text":"lamb", "phonemes":"L AE M"},
    {"text":"lamp", "phonemes":"L AE M P"},
    {"text":"lan", "phonemes":"L AE N"},
    {"text":"land", "phonemes":"L AE N D"},
    {"text":"landmine", "phonemes":"L AE N D M AY N"},
    {"text":"language", "phonemes":"L AE NG G W AH JH"},
    {"text":"larch", "phonemes":"L AA R CH"},
    {"text":"lasagna", "phonemes":"L AA S AA N Y AH"},
    {"text":"latency", "phonemes":"L EY T AH N S IY"},
    {"text":"latex", "phonemes":"L EY T EH K S"},
    {"text":"lathe", "phonemes":"L EY DH"},
    {"text":"laugh", "phonemes":"L AE F"},
    {"text":"laundry", "phonemes":"L AO N D R IY"},
    {"text":"law", "phonemes":"L AO"},
    {"text":"lawyer", "phonemes":"L AO Y ER"},
    {"text":"layer", "phonemes":"L EY ER"},
    {"text":"lead", "phonemes":"L EH D"},
    {"text":"leaf", "phonemes":"L IY F"},
    {"text":"leather", "phonemes":"L EH DH ER"},
    {"text":"leek", "phonemes":"L IY K"},
    {"text":"leg", "phonemes":"L EH G"},
    {"text":"legal", "phonemes":"L IY G AH L"},
    {"text":"lemonade", "phonemes":"L EH M AH N EY D"},
    {"text":"lentil", "phonemes":"L EH N T AH L"},
    {"text":"leopard", "phonemes":"L EH P ER D"},
    {"text":"letter", "phonemes":"L EH T ER"},
    {"text":"lettuce", "phonemes":"L EH T AH S"},
    {"text":"library", "phonemes":"L AY B R EH R IY"},
    {"text":"license", "phonemes":"L AY S AH N S"},
    {"text":"lilac", "phonemes":"L AY L AE K"},
    {"text":"lily", "phonemes":"L IH L IY"},
    {"text":"line", "phonemes":"L AY N"},
    {"text":"linen", "phonemes":"L IH N AH N"},
    {"text":"link", "phonemes":"L IH NG K"},
    {"text":"lion", "phonemes":"L AY AH N"},
    {"text":"lip", "phonemes":"L IH P"},
    {"text":"lipstick", "phonemes":"L IH P S T IH K"},
    {"text":"liquid", "phonemes":"L IH K W AH D"},
    {"text":"liquor", "phonemes":"L IH K ER"},
    {"text":"literature", "phonemes":"L IH T ER AH CH ER"},
    {"text":"litter", "phonemes":"L IH T ER"},
    {"text":"liver", "phonemes":"L IH V ER"},
    {"text":"lizard", "phonemes":"L IH Z ER D"},
    {"text":"llama", "phonemes":"L AA M AH"},
    {"text":"loaf", "phonemes":"L OW F"},
    {"text":"loan", "phonemes":"L OW N"},
    {"text":"lobster", "phonemes":"L AA B S T ER"},
    {"text":"lock", "phonemes":"L AA K"},
    {"text":"locket", "phonemes":"L AA K IH T"},
    {"text":"locust", "phonemes":"L OW K AH S T"},
    {"text":"look", "phonemes":"L UH K"},
    {"text":"lotion", "phonemes":"L OW SH AH N"},
    {"text":"love", "phonemes":"L AH V"},
    {"text":"low", "phonemes":"L OW"},
    {"text":"lumber", "phonemes":"L AH M B ER"},
    {"text":"lunch", "phonemes":"L AH N CH"},
    {"text":"lunchroom", "phonemes":"L AH N CH R UW M"},
    {"text":"lung", "phonemes":"L AH NG"},
    {"text":"lunge", "phonemes":"L AH N JH"},
    {"text":"lute", "phonemes":"L UW T"},
    {"text":"lycra", "phonemes":"L AY K R AH"},
    {"text":"lynx", "phonemes":"L IH NG K S"},
    {"text":"lyre", "phonemes":"L AY R"},
    {"text":"lyric", "phonemes":"L IH R IH K"},
    {"text":"macaroni", "phonemes":"M AE K ER OW N IY"},
    {"text":"machine", "phonemes":"M AH SH IY N"},
    {"text":"macrame", "phonemes":"M AE K R AH M EY"},
    {"text":"magazine", "phonemes":"M AE G AH Z IY N"},
    {"text":"magic", "phonemes":"M AE JH IH K"},
    {"text":"magician", "phonemes":"M AH JH IH SH AH N"},
    {"text":"maid", "phonemes":"M EY D"},
    {"text":"mail", "phonemes":"M EY L"},
    {"text":"mailbox", "phonemes":"M EY L B AA K S"},
    {"text":"mailman", "phonemes":"M EY L M AE N"},
    {"text":"makeup", "phonemes":"M EY K AH P"},
    {"text":"malaysia", "phonemes":"M AH L EY ZH AH"},
    {"text":"male", "phonemes":"M EY L"},
    {"text":"mall", "phonemes":"M AO L"},
    {"text":"mallet", "phonemes":"M AE L IH T"},
    {"text":"man", "phonemes":"M AE N"},
    {"text":"manager", "phonemes":"M AE N AH JH ER"},
    {"text":"mandolin", "phonemes":"M AE N D AH L IH N"},
    {"text":"manicure", "phonemes":"M AE N IH K Y ER"},
    {"text":"map", "phonemes":"M AE P"},
    {"text":"maple", "phonemes":"M EY P AH L"},
    {"text":"maraca", "phonemes":"M AE R AH K AH"},
    {"text":"marble", "phonemes":"M AA R B AH L"},
    {"text":"march", "phonemes":"M AA R CH"},
    {"text":"marimba", "phonemes":"M ER IH M B AH"},
    {"text":"mark", "phonemes":"M AA R K"},
    {"text":"market", "phonemes":"M AA R K AH T"},
    {"text":"married", "phonemes":"M EH R IY D"},
    {"text":"mascara", "phonemes":"M AE S K EH R AH"},
    {"text":"mask", "phonemes":"M AE S K"},
    {"text":"mass", "phonemes":"M AE S"},
    {"text":"match", "phonemes":"M AE CH"},
    {"text":"math", "phonemes":"M AE TH"},
    {"text":"mattock", "phonemes":"M AE T AH K"},
    {"text":"mayonnaise", "phonemes":"M EY AH N EY Z"},
    {"text":"meal", "phonemes":"M IY L"},
    {"text":"measure", "phonemes":"M EH ZH ER"},
    {"text":"meat", "phonemes":"M IY T"},
    {"text":"mechanic", "phonemes":"M AH K AE N IH K"},
    {"text":"medicine", "phonemes":"M EH D AH S AH N"},
    {"text":"meeting", "phonemes":"M IY T IH NG"},
    {"text":"melody", "phonemes":"M EH L AH D IY"},
    {"text":"memory", "phonemes":"M EH M ER IY"},
    {"text":"men", "phonemes":"M EH N"},
    {"text":"menu", "phonemes":"M EH N Y UW"},
    {"text":"mercury", "phonemes":"M ER K Y ER IY"},
    {"text":"message", "phonemes":"M EH S AH JH"},
    {"text":"metal", "phonemes":"M EH T AH L"},
    {"text":"meteorology", "phonemes":"M IY T IY ER AA L AH JH IY"},
    {"text":"meter", "phonemes":"M IY T ER"},
    {"text":"mice", "phonemes":"M AY S"},
    {"text":"microwave", "phonemes":"M AY K R AH W EY V"},
    {"text":"middle", "phonemes":"M IH D AH L"},
    {"text":"mile", "phonemes":"M AY L"},
    {"text":"milk", "phonemes":"M IH L K"},
    {"text":"milkshake", "phonemes":"M IH L K SH EY K"},
    {"text":"millennium", "phonemes":"M AH L EH N IY AH M"},
    {"text":"millimeter", "phonemes":"M IH L AH M IY T ER"},
    {"text":"millisecond", "phonemes":"M IH L IH S EH K AH N D"},
    {"text":"mimosa", "phonemes":"M IH M OW S AH"},
    {"text":"mind", "phonemes":"M AY N D"},
    {"text":"mine", "phonemes":"M AY N"},
    {"text":"minibus", "phonemes":"M IH N IY B AH S"},
    {"text":"mini", "phonemes":"-SKIRT	M IH N IY S K ER T"},
    {"text":"minister", "phonemes":"M IH N AH S T ER"},
    {"text":"mint", "phonemes":"M IH N T"},
    {"text":"minute", "phonemes":"M IH N AH T"},
    {"text":"mirror", "phonemes":"M IH R ER"},
    {"text":"missile", "phonemes":"M IH S AH L"},
    {"text":"mist", "phonemes":"M IH S T"},
    {"text":"mistake", "phonemes":"M IH S T EY K"},
    {"text":"mitten", "phonemes":"M IH T AH N"},
    {"text":"moat", "phonemes":"M OW T"},
    {"text":"modem", "phonemes":"M OW D AH M"},
    {"text":"mole", "phonemes":"M OW L"},
    {"text":"mom", "phonemes":"M AA M"},
    {"text":"money", "phonemes":"M AH N IY"},
    {"text":"monkey", "phonemes":"M AH NG K IY"},
    {"text":"month", "phonemes":"M AH N TH"},
    {"text":"moon", "phonemes":"M UW N"},
    {"text":"morning", "phonemes":"M AO R N IH NG"},
    {"text":"morocco", "phonemes":"M ER AA K OW"},
    {"text":"mosque", "phonemes":"M AA S K"},
    {"text":"mosquito", "phonemes":"M AH S K IY T OW"},
    {"text":"mother", "phonemes":"M AH DH ER"},
    {"text":"mother", "phonemes":"-IN-LAW	M AH DH ER IH N L AO"},
    {"text":"motion", "phonemes":"M OW SH AH N"},
    {"text":"motorboat", "phonemes":"M OW T ER B OW T"},
    {"text":"motorcycle", "phonemes":"M OW T ER S AY K AH L"},
    {"text":"mountain", "phonemes":"M AW N T AH N"},
    {"text":"mouse", "phonemes":"M AW S"},
    {"text":"moustache", "phonemes":"M AH S T AE SH"},
    {"text":"mouth", "phonemes":"M AW TH"},
    {"text":"multimedia", "phonemes":"M AH L T IY M IY D IY AH"},
    {"text":"muscle", "phonemes":"M AH S AH L"},
    {"text":"museum", "phonemes":"M Y UW Z IY AH M"},
    {"text":"music", "phonemes":"M Y UW Z IH K"},
    {"text":"musician", "phonemes":"M Y UW Z IH SH AH N"},
    {"text":"mustard", "phonemes":"M AH S T ER D"},
    {"text":"nail", "phonemes":"N EY L"},
    {"text":"name", "phonemes":"N EY M"},
    {"text":"nancy", "phonemes":"N AE N S IY"},
    {"text":"napkin", "phonemes":"N AE P K IH N"},
    {"text":"nation", "phonemes":"N EY SH AH N"},
    {"text":"neck", "phonemes":"N EH K"},
    {"text":"need", "phonemes":"N IY D"},
    {"text":"needle", "phonemes":"N IY D AH L"},
    {"text":"neon", "phonemes":"N IY AA N"},
    {"text":"nephew", "phonemes":"N EH F Y UW"},
    {"text":"nerve", "phonemes":"N ER V"},
    {"text":"nest", "phonemes":"N EH S T"},
    {"text":"net", "phonemes":"N EH T"},
    {"text":"network", "phonemes":"N EH T W ER K"},
    {"text":"newsprint", "phonemes":"N UW Z P R IH N T"},
    {"text":"newsstand", "phonemes":"N UW Z S T AE N D"},
    {"text":"nic", "phonemes":"N IH K"},
    {"text":"nickel", "phonemes":"N IH K AH L"},
    {"text":"niece", "phonemes":"N IY S"},
    {"text":"night", "phonemes":"N AY T"},
    {"text":"nitrogen", "phonemes":"N AY T R AH JH AH N"},
    {"text":"node", "phonemes":"N OW D"},
    {"text":"noise", "phonemes":"N OY Z"},
    {"text":"noodle", "phonemes":"N UW D AH L"},
    {"text":"nose", "phonemes":"N OW Z"},
    {"text":"note", "phonemes":"N OW T"},
    {"text":"notebook", "phonemes":"N OW T B UH K"},
    {"text":"notify", "phonemes":"N OW T AH F AY"},
    {"text":"novel", "phonemes":"N AA V AH L"},
    {"text":"number", "phonemes":"N AH M B ER"},
    {"text":"numeric", "phonemes":"N UW M EH R IH K"},
    {"text":"nurse", "phonemes":"N ER S"},
    {"text":"nut", "phonemes":"N AH T"},
    {"text":"nylon", "phonemes":"N AY L AA N"},
    {"text":"oak", "phonemes":"OW K"},
    {"text":"oatmeal", "phonemes":"OW T M IY L"},
    {"text":"objective", "phonemes":"AH B JH EH K T IH V"},
    {"text":"oboe", "phonemes":"OW B OW"},
    {"text":"observation", "phonemes":"AA B Z ER V EY SH AH N"},
    {"text":"occupation", "phonemes":"AA K Y AH P EY SH AH N"},
    {"text":"ocean", "phonemes":"OW SH AH N"},
    {"text":"ocelot", "phonemes":"AA S AH L AA T"},
    {"text":"octagon", "phonemes":"AA K T AH G AA N"},
    {"text":"octave", "phonemes":"AA K T IH V"},
    {"text":"october", "phonemes":"AA K T OW B ER"},
    {"text":"octopus", "phonemes":"AA K T AH P UH S"},
    {"text":"odometer", "phonemes":"OW D AA M AH T ER"},
    {"text":"offence", "phonemes":"AH F EH N S"},
    {"text":"offer", "phonemes":"AO F ER"},
    {"text":"office", "phonemes":"AO F AH S"},
    {"text":"oil", "phonemes":"OY L"},
    {"text":"okra", "phonemes":"OW K R AH"},
    {"text":"olive", "phonemes":"AA L AH V"},
    {"text":"onion", "phonemes":"AH N Y AH N"},
    {"text":"open", "phonemes":"OW P AH N"},
    {"text":"opera", "phonemes":"AA P R AH"},
    {"text":"operation", "phonemes":"AA P ER EY SH AH N"},
    {"text":"ophthalmologist", "phonemes":"AA P TH AH M AA L AH JH IH S T"},
    {"text":"orange", "phonemes":"AO R AH N JH"},
    {"text":"orchestra", "phonemes":"AO R K AH S T R AH"},
    {"text":"orchid", "phonemes":"AO R K AH D"},
    {"text":"order", "phonemes":"AO R D ER"},
    {"text":"organ", "phonemes":"AO R G AH N"},
    {"text":"organisation", "phonemes":"AO R G AH N IH Z EY SH AH N"},
    {"text":"organization", "phonemes":"AO R G AH N AH Z EY SH AH N"},
    {"text":"ornament", "phonemes":"AO R N AH M AH N T"},
    {"text":"ostrich", "phonemes":"AO S T R IH CH"},
    {"text":"otter", "phonemes":"AA T ER"},
    {"text":"ounce", "phonemes":"AW N S"},
    {"text":"output", "phonemes":"AW T P UH T"},
    {"text":"outrigger", "phonemes":"AW T R IH G ER"},
    {"text":"oven", "phonemes":"AH V AH N"},
    {"text":"overcoat", "phonemes":"OW V ER K OW T"},
    {"text":"owl", "phonemes":"AW L"},
    {"text":"ox", "phonemes":"AA K S"},
    {"text":"oxygen", "phonemes":"AA K S AH JH AH N"},
    {"text":"oyster", "phonemes":"OY S T ER"},
    {"text":"page", "phonemes":"P EY JH"},
    {"text":"pail", "phonemes":"P EY L"},
    {"text":"paint", "phonemes":"P EY N T"},
    {"text":"pair", "phonemes":"P EH R"},
    {"text":"pajama", "phonemes":"P AH JH AA M AH"},
    {"text":"palm", "phonemes":"P AA M"},
    {"text":"pamphlet", "phonemes":"P AE M F L AH T"},
    {"text":"pan", "phonemes":"P AE N"},
    {"text":"pancake", "phonemes":"P AE N K EY K"},
    {"text":"pancreas", "phonemes":"P AE N K R IY AH S"},
    {"text":"panda", "phonemes":"P AE N D AH"},
    {"text":"pansy", "phonemes":"P AE N Z IY"},
    {"text":"panther", "phonemes":"P AE N TH ER"},
    {"text":"pantry", "phonemes":"P AE N T R IY"},
    {"text":"pairofpants", "phonemes":"P AE AH R AA F AH N T S"},
    {"text":"panty", "phonemes":"P AE N T IY"},
    {"text":"pantyhose", "phonemes":"P AE N T IY HH OW Z"},
    {"text":"paper", "phonemes":"P EY P ER"},
    {"text":"paperback", "phonemes":"P EY P ER B AE K"},
    {"text":"parade", "phonemes":"P ER EY D"},
    {"text":"parallelogram", "phonemes":"P AH R AE L AH L AA G R AH M"},
    {"text":"parcel", "phonemes":"P AA R S AH L"},
    {"text":"parent", "phonemes":"P EH R AH N T"},
    {"text":"parenthesis", "phonemes":"P ER EH N TH AH S IH S"},
    {"text":"park", "phonemes":"P AA R K"},
    {"text":"parrot", "phonemes":"P EH R AH T"},
    {"text":"parsnip", "phonemes":"P AA R S N IH P"},
    {"text":"partner", "phonemes":"P AA R T N ER"},
    {"text":"partridge", "phonemes":"P AA R T R AH JH"},
    {"text":"party", "phonemes":"P AA R T IY"},
    {"text":"passbook", "phonemes":"P AE S B UH K"},
    {"text":"passenger", "phonemes":"P AE S AH N JH ER"},
    {"text":"pasta", "phonemes":"P AA S T AH"},
    {"text":"paste", "phonemes":"P EY S T"},
    {"text":"pastor", "phonemes":"P AE S T ER"},
    {"text":"pastry", "phonemes":"P EY S T R IY"},
    {"text":"patch", "phonemes":"P AE CH"},
    {"text":"path", "phonemes":"P AE TH"},
    {"text":"patient", "phonemes":"P EY SH AH N T"},
    {"text":"patio", "phonemes":"P AE T IY OW"},
    {"text":"payment", "phonemes":"P EY M AH N T"},
    {"text":"pea", "phonemes":"P IY"},
    {"text":"peace", "phonemes":"P IY S"},
    {"text":"peak", "phonemes":"P IY K"},
    {"text":"peanut", "phonemes":"P IY N AH T"},
    {"text":"pear", "phonemes":"P EH R"},
    {"text":"pedestrian", "phonemes":"P AH D EH S T R IY AH N"},
    {"text":"pediatrician", "phonemes":"P IY D IY AH T R IH SH AH N"},
    {"text":"pelican", "phonemes":"P EH L AH K AH N"},
    {"text":"pen", "phonemes":"P EH N"},
    {"text":"penalty", "phonemes":"P EH N AH L T IY"},
    {"text":"pencil", "phonemes":"P EH N S AH L"},
    {"text":"pendulum", "phonemes":"P EH N JH AH L AH M"},
    {"text":"pentagon", "phonemes":"P EH N T IH G AA N"},
    {"text":"peony", "phonemes":"P IY AH N IY"},
    {"text":"pepper", "phonemes":"P EH P ER"},
    {"text":"perch", "phonemes":"P ER CH"},
    {"text":"perfume", "phonemes":"P ER F Y UW M"},
    {"text":"period", "phonemes":"P IH R IY AH D"},
    {"text":"pest", "phonemes":"P EH S T"},
    {"text":"pet", "phonemes":"P EH T"},
    {"text":"pharmacist", "phonemes":"F AA R M AH S IH S T"},
    {"text":"pheasant", "phonemes":"F EH Z AH N T"},
    {"text":"phone", "phonemes":"F OW N"},
    {"text":"physician", "phonemes":"F AH Z IH SH AH N"},
    {"text":"piano", "phonemes":"P IY AE N OW"},
    {"text":"pickle", "phonemes":"P IH K AH L"},
    {"text":"picture", "phonemes":"P IH K CH ER"},
    {"text":"pie", "phonemes":"P AY"},
    {"text":"pig", "phonemes":"P IH G"},
    {"text":"pigeon", "phonemes":"P IH JH AH N"},
    {"text":"pike", "phonemes":"P AY K"},
    {"text":"pillow", "phonemes":"P IH L OW"},
    {"text":"pilot", "phonemes":"P AY L AH T"},
    {"text":"pimple", "phonemes":"P IH M P AH L"},
    {"text":"pin", "phonemes":"P IH N"},
    {"text":"pine", "phonemes":"P AY N"},
    {"text":"ping", "phonemes":"P IH NG"},
    {"text":"pint", "phonemes":"P AY N T"},
    {"text":"pipe", "phonemes":"P AY P"},
    {"text":"pisces", "phonemes":"P AY S IY Z"},
    {"text":"pizza", "phonemes":"P IY T S AH"},
    {"text":"place", "phonemes":"P L EY S"},
    {"text":"plain", "phonemes":"P L EY N"},
    {"text":"plane", "phonemes":"P L EY N"},
    {"text":"planet", "phonemes":"P L AE N AH T"},
    {"text":"plant", "phonemes":"P L AE N T"},
    {"text":"plantation", "phonemes":"P L AE N T EY SH AH N"},
    {"text":"plastic", "phonemes":"P L AE S T IH K"},
    {"text":"plate", "phonemes":"P L EY T"},
    {"text":"platinum", "phonemes":"P L AE T N AH M"},
    {"text":"play", "phonemes":"P L EY"},
    {"text":"playground", "phonemes":"P L EY G R AW N D"},
    {"text":"playroom", "phonemes":"P L EY R UW M"},
    {"text":"pleasure", "phonemes":"P L EH ZH ER"},
    {"text":"plier", "phonemes":"P L AY ER"},
    {"text":"plot", "phonemes":"P L AA T"},
    {"text":"plow", "phonemes":"P L AW"},
    {"text":"plywood", "phonemes":"P L AY W UH D"},
    {"text":"pocket", "phonemes":"P AA K AH T"},
    {"text":"poet", "phonemes":"P OW AH T"},
    {"text":"point", "phonemes":"P OY N T"},
    {"text":"poison", "phonemes":"P OY Z AH N"},
    {"text":"policeman", "phonemes":"P AH L IY S M AH N"},
    {"text":"polish", "phonemes":"P AA L IH SH"},
    {"text":"politician", "phonemes":"P AA L AH T IH SH AH N"},
    {"text":"pond", "phonemes":"P AA N D"},
    {"text":"popcorn", "phonemes":"P AA P K AO R N"},
    {"text":"poppy", "phonemes":"P AA P IY"},
    {"text":"population", "phonemes":"P AA P Y AH L EY SH AH N"},
    {"text":"porch", "phonemes":"P AO R CH"},
    {"text":"porcupine", "phonemes":"P AO R K Y AH P AY N"},
    {"text":"port", "phonemes":"P AO R T"},
    {"text":"porter", "phonemes":"P AO R T ER"},
    {"text":"postage", "phonemes":"P OW S T AH JH"},
    {"text":"postbox", "phonemes":"P OW S T B AA K S"},
    {"text":"potato", "phonemes":"P AH T EY T OW"},
    {"text":"poultry", "phonemes":"P OW L T R IY"},
    {"text":"pound", "phonemes":"P AW N D"},
    {"text":"powder", "phonemes":"P AW D ER"},
    {"text":"power", "phonemes":"P AW ER"},
    {"text":"preface", "phonemes":"P R EH F AH S"},
    {"text":"price", "phonemes":"P R AY S"},
    {"text":"priest", "phonemes":"P R IY S T"},
    {"text":"print", "phonemes":"P R IH N T"},
    {"text":"printer", "phonemes":"P R IH N T ER"},
    {"text":"prison", "phonemes":"P R IH Z AH N"},
    {"text":"produce", "phonemes":"P R AH D UW S"},
    {"text":"product", "phonemes":"P R AA D AH K T"},
    {"text":"production", "phonemes":"P R AH D AH K SH AH N"},
    {"text":"professor", "phonemes":"P R AH F EH S ER"},
    {"text":"propane", "phonemes":"P R OW P EY N"},
    {"text":"property", "phonemes":"P R AA P ER T IY"},
    {"text":"prose", "phonemes":"P R OW Z"},
    {"text":"prosecution", "phonemes":"P R AA S AH K Y UW SH AH N"},
    {"text":"protest", "phonemes":"P R OW T EH S T"},
    {"text":"protocol", "phonemes":"P R OW T AH K AA L"},
    {"text":"pruner", "phonemes":"P R UW N ER"},
    {"text":"psychiatrist", "phonemes":"S AH K AY AH T R AH S T"},
    {"text":"psychology", "phonemes":"S AY K AA L AH JH IY"},
    {"text":"ptarmigan", "phonemes":"T AA R M AH G AH N"},
    {"text":"puffin", "phonemes":"P AH F IH N"},
    {"text":"puma", "phonemes":"P UW M AH"},
    {"text":"pump", "phonemes":"P AH M P"},
    {"text":"pumpkin", "phonemes":"P AH M P K IH N"},
    {"text":"punch", "phonemes":"P AH N CH"},
    {"text":"punishment", "phonemes":"P AH N IH SH M AH N T"},
    {"text":"puppy", "phonemes":"P AH P IY"},
    {"text":"pyramid", "phonemes":"P IH R AH M IH D"},
    {"text":"quail", "phonemes":"K W EY L"},
    {"text":"quarter", "phonemes":"K W AO R T ER"},
    {"text":"quartz", "phonemes":"K W AO R T S"},
    {"text":"queen", "phonemes":"K W IY N"},
    {"text":"quicksand", "phonemes":"K W IH K S AE N D"},
    {"text":"quilt", "phonemes":"K W IH L T"},
    {"text":"quince", "phonemes":"K W IH N S"},
    {"text":"quiver", "phonemes":"K W IH V ER"},
    {"text":"rabbi", "phonemes":"R AE B AY"},
    {"text":"rabbit", "phonemes":"R AE B AH T"},
    {"text":"radar", "phonemes":"R EY D AA R"},
    {"text":"radiator", "phonemes":"R EY D IY EY T ER"},
    {"text":"radio", "phonemes":"R EY D IY OW"},
    {"text":"radish", "phonemes":"R AE D IH SH"},
    {"text":"raft", "phonemes":"R AE F T"},
    {"text":"rail", "phonemes":"R EY L"},
    {"text":"rain", "phonemes":"R EY N"},
    {"text":"rainbow", "phonemes":"R EY N B OW"},
    {"text":"raincoat", "phonemes":"R EY N K OW T"},
    {"text":"rainstorm", "phonemes":"R EY N S T AO R M"},
    {"text":"rake", "phonemes":"R EY K"},
    {"text":"random", "phonemes":"R AE N D AH M"},
    {"text":"range", "phonemes":"R EY N JH"},
    {"text":"rat", "phonemes":"R AE T"},
    {"text":"rate", "phonemes":"R EY T"},
    {"text":"raven", "phonemes":"R EY V AH N"},
    {"text":"reaction", "phonemes":"R IY AE K SH AH N"},
    {"text":"reading", "phonemes":"R IY D IH NG"},
    {"text":"receipt", "phonemes":"R IH S IY T"},
    {"text":"record", "phonemes":"R AH K AO R D"},
    {"text":"recorder", "phonemes":"R IH K AO R D ER"},
    {"text":"reduction", "phonemes":"R IH D AH K SH AH N"},
    {"text":"refrigerator", "phonemes":"R AH F R IH JH ER EY T ER"},
    {"text":"refund", "phonemes":"R IH F AH N D"},
    {"text":"reindeer", "phonemes":"R EY N D IH R"},
    {"text":"relation", "phonemes":"R IY L EY SH AH N"},
    {"text":"report", "phonemes":"R IY P AO R T"},
    {"text":"representative", "phonemes":"R EH P R AH Z EH N T AH T IH V"},
    {"text":"request", "phonemes":"R IH K W EH S T"},
    {"text":"resolution", "phonemes":"R EH Z AH L UW SH AH N"},
    {"text":"respect", "phonemes":"R IH S P EH K T"},
    {"text":"restaurant", "phonemes":"R EH S T ER AA N T"},
    {"text":"result", "phonemes":"R IH Z AH L T"},
    {"text":"retailer", "phonemes":"R IY T EY L ER"},
    {"text":"revolve", "phonemes":"R IY V AA L V"},
    {"text":"revolver", "phonemes":"R IH V AA L V ER"},
    {"text":"reward", "phonemes":"R IH W AO R D"},
    {"text":"rhinoceros", "phonemes":"R AY N AA S ER AH S"},
    {"text":"rhythm", "phonemes":"R IH DH AH M"},
    {"text":"rice", "phonemes":"R AY S"},
    {"text":"riddle", "phonemes":"R IH D AH L"},
    {"text":"rifle", "phonemes":"R AY F AH L"},
    {"text":"ring", "phonemes":"R IH NG"},
    {"text":"rise", "phonemes":"R AY Z"},
    {"text":"river", "phonemes":"R IH V ER"},
    {"text":"riverbed", "phonemes":"R IH V ER B EH D"},
    {"text":"road", "phonemes":"R OW D"},
    {"text":"roadway", "phonemes":"R OW D W EY"},
    {"text":"roast", "phonemes":"R OW S T"},
    {"text":"rock", "phonemes":"R AA K"},
    {"text":"rocket", "phonemes":"R AA K AH T"},
    {"text":"rod", "phonemes":"R AA D"},
    {"text":"roll", "phonemes":"R OW L"},
    {"text":"roof", "phonemes":"R UW F"},
    {"text":"room", "phonemes":"R UW M"},
    {"text":"rooster", "phonemes":"R UW S T ER"},
    {"text":"root", "phonemes":"R UW T"},
    {"text":"rose", "phonemes":"R OW Z"},
    {"text":"router", "phonemes":"R UW T ER"},
    {"text":"rowboat", "phonemes":"R OW B OW T"},
    {"text":"rub", "phonemes":"R AH B"},
    {"text":"rubber", "phonemes":"R AH B ER"},
    {"text":"rugby", "phonemes":"R AH G B IY"},
    {"text":"rutabaga", "phonemes":"R UW T AH B EY G AH"},
    {"text":"sail", "phonemes":"S EY L"},
    {"text":"sailboat", "phonemes":"S EY L B OW T"},
    {"text":"sailor", "phonemes":"S EY L ER"},
    {"text":"salad", "phonemes":"S AE L AH D"},
    {"text":"salmon", "phonemes":"S AE M AH N"},
    {"text":"salt", "phonemes":"S AO L T"},
    {"text":"sampan", "phonemes":"S AE M P AE N"},
    {"text":"samurai", "phonemes":"S AE M UH R AY"},
    {"text":"sand", "phonemes":"S AE N D"},
    {"text":"sandwich", "phonemes":"S AE N D W IH CH"},
    {"text":"santa", "phonemes":"S AE N T AH"},
    {"text":"sardine", "phonemes":"S AA R D IY N"},
    {"text":"satin", "phonemes":"S AE T AH N"},
    {"text":"sauce", "phonemes":"S AO S"},
    {"text":"sausage", "phonemes":"S AO S AH JH"},
    {"text":"save", "phonemes":"S EY V"},
    {"text":"saw", "phonemes":"S AO"},
    {"text":"saxophone", "phonemes":"S AE K S AH F OW N"},
    {"text":"scale", "phonemes":"S K EY L"},
    {"text":"scallion", "phonemes":"S K AE L Y AH N"},
    {"text":"scanner", "phonemes":"S K AE N ER"},
    {"text":"scarecrow", "phonemes":"S K AE R K R OW"},
    {"text":"scarf", "phonemes":"S K AA R F"},
    {"text":"scene", "phonemes":"S IY N"},
    {"text":"scent", "phonemes":"S EH N T"},
    {"text":"schedule", "phonemes":"S K EH JH UH L"},
    {"text":"school", "phonemes":"S K UW L"},
    {"text":"science", "phonemes":"S AY AH N S"},
    {"text":"scissor", "phonemes":"S IH Z ER"},
    {"text":"scooter", "phonemes":"S K UW T ER"},
    {"text":"scorpion", "phonemes":"S K AO R P IY AH N"},
    {"text":"scraper", "phonemes":"S K R EY P ER"},
    {"text":"screen", "phonemes":"S K R IY N"},
    {"text":"screw", "phonemes":"S K R UW"},
    {"text":"screwdriver", "phonemes":"S K R UW D R AY V ER"},
    {"text":"seagull", "phonemes":"S IY G AH L"},
    {"text":"seal", "phonemes":"S IY L"},
    {"text":"seaplane", "phonemes":"S IY P L EY N"},
    {"text":"search", "phonemes":"S ER CH"},
    {"text":"seashore", "phonemes":"S IY SH AO R"},
    {"text":"season", "phonemes":"S IY Z AH N"},
    {"text":"seat", "phonemes":"S IY T"},
    {"text":"second", "phonemes":"S EH K AH N D"},
    {"text":"secretary", "phonemes":"S EH K R AH T EH R IY"},
    {"text":"secure", "phonemes":"S IH K Y UH R"},
    {"text":"security", "phonemes":"S IH K Y UH R AH T IY"},
    {"text":"seed", "phonemes":"S IY D"},
    {"text":"segment", "phonemes":"S EH G M AH N T"},
    {"text":"selection", "phonemes":"S AH L EH K SH AH N"},
    {"text":"self", "phonemes":"S EH L F"},
    {"text":"semicircle", "phonemes":"S EH M IY S ER K AH L"},
    {"text":"semicolon", "phonemes":"S EH M IY K OW L AH N"},
    {"text":"sense", "phonemes":"S EH N S"},
    {"text":"sentence", "phonemes":"S EH N T AH N S"},
    {"text":"separated", "phonemes":"S EH P ER EY T AH D"},
    {"text":"servant", "phonemes":"S ER V AH N T"},
    {"text":"server", "phonemes":"S ER V ER"},
    {"text":"session", "phonemes":"S EH SH AH N"},
    {"text":"sex", "phonemes":"S EH K S"},
    {"text":"shade", "phonemes":"SH EY D"},
    {"text":"shadow", "phonemes":"SH AE D OW"},
    {"text":"shake", "phonemes":"SH EY K"},
    {"text":"shallot", "phonemes":"SH AE L AH T"},
    {"text":"shame", "phonemes":"SH EY M"},
    {"text":"shampoo", "phonemes":"SH AE M P UW"},
    {"text":"shape", "phonemes":"SH EY P"},
    {"text":"share", "phonemes":"SH EH R"},
    {"text":"shark", "phonemes":"SH AA R K"},
    {"text":"sheep", "phonemes":"SH IY P"},
    {"text":"shield", "phonemes":"SH IY L D"},
    {"text":"shingle", "phonemes":"SH IH NG G AH L"},
    {"text":"ship", "phonemes":"SH IH P"},
    {"text":"shirt", "phonemes":"SH ER T"},
    {"text":"shock", "phonemes":"SH AA K"},
    {"text":"shoe", "phonemes":"SH UW"},
    {"text":"shoemaker", "phonemes":"SH UW M EY K ER"},
    {"text":"shop", "phonemes":"SH AA P"},
    {"text":"shoulder", "phonemes":"SH OW L D ER"},
    {"text":"shovel", "phonemes":"SH AH V AH L"},
    {"text":"show", "phonemes":"SH OW"},
    {"text":"shrimp", "phonemes":"SH R IH M P"},
    {"text":"shrine", "phonemes":"SH R AY N"},
    {"text":"sideboard", "phonemes":"S AY D B OW R D"},
    {"text":"sign", "phonemes":"S AY N"},
    {"text":"signature", "phonemes":"S IH G N AH CH ER"},
    {"text":"silica", "phonemes":"S IH L AH K AH"},
    {"text":"silk", "phonemes":"S IH L K"},
    {"text":"silver", "phonemes":"S IH L V ER"},
    {"text":"sing", "phonemes":"S IH NG"},
    {"text":"singer", "phonemes":"S IH NG ER"},
    {"text":"single", "phonemes":"S IH NG G AH L"},
    {"text":"sink", "phonemes":"S IH NG K"},
    {"text":"sister", "phonemes":"S IH S T ER"},
    {"text":"sister", "phonemes":"-IN-LAW	S IH S T ER IH N L AO"},
    {"text":"skate", "phonemes":"S K EY T"},
    {"text":"ski", "phonemes":"S K IY"},
    {"text":"skill", "phonemes":"S K IH L"},
    {"text":"skin", "phonemes":"S K IH N"},
    {"text":"skirt", "phonemes":"S K ER T"},
    {"text":"sky", "phonemes":"S K AY"},
    {"text":"slash", "phonemes":"S L AE SH"},
    {"text":"slave", "phonemes":"S L EY V"},
    {"text":"sled", "phonemes":"S L EH D"},
    {"text":"sleep", "phonemes":"S L IY P"},
    {"text":"sleet", "phonemes":"S L IY T"},
    {"text":"slice", "phonemes":"S L AY S"},
    {"text":"slime", "phonemes":"S L AY M"},
    {"text":"slipper", "phonemes":"S L IH P ER"},
    {"text":"slope", "phonemes":"S L OW P"},
    {"text":"smash", "phonemes":"S M AE SH"},
    {"text":"smell", "phonemes":"S M EH L"},
    {"text":"smile", "phonemes":"S M AY L"},
    {"text":"smoke", "phonemes":"S M OW K"},
    {"text":"snail", "phonemes":"S N EY L"},
    {"text":"snake", "phonemes":"S N EY K"},
    {"text":"sneeze", "phonemes":"S N IY Z"},
    {"text":"snow", "phonemes":"S N OW"},
    {"text":"snowboard", "phonemes":"S N OW B AO R D"},
    {"text":"snowflake", "phonemes":"S N OW F L EY K"},
    {"text":"snowman", "phonemes":"S N OW M AE N"},
    {"text":"snowplow", "phonemes":"S N OW P L AW"},
    {"text":"snowstorm", "phonemes":"S N OW S T AO R M"},
    {"text":"soap", "phonemes":"S OW P"},
    {"text":"soccer", "phonemes":"S AA K ER"},
    {"text":"sock", "phonemes":"S AA K"},
    {"text":"soda", "phonemes":"S OW D AH"},
    {"text":"sofa", "phonemes":"S OW F AH"},
    {"text":"softball", "phonemes":"S AO F T B AO L"},
    {"text":"softdrink", "phonemes":"S AO F T D R IH NG K"},
    {"text":"software", "phonemes":"S AO F T W EH R"},
    {"text":"soil", "phonemes":"S OY L"},
    {"text":"soldier", "phonemes":"S OW L JH ER"},
    {"text":"son", "phonemes":"S AH N"},
    {"text":"song", "phonemes":"S AO NG"},
    {"text":"soprano", "phonemes":"S AH P R AA N OW"},
    {"text":"sort", "phonemes":"S AO R T"},
    {"text":"sound", "phonemes":"S AW N D"},
    {"text":"soup", "phonemes":"S UW P"},
    {"text":"sousaphone", "phonemes":"S UW Z AH F OW N"},
    {"text":"soy", "phonemes":"S OY"},
    {"text":"soybean", "phonemes":"S OY B IY N"},
    {"text":"space", "phonemes":"S P EY S"},
    {"text":"spade", "phonemes":"S P EY D"},
    {"text":"spaghetti", "phonemes":"S P AH G EH T IY"},
    {"text":"spandex", "phonemes":"S P AE N D AH K S"},
    {"text":"spark", "phonemes":"S P AA R K"},
    {"text":"sparrow", "phonemes":"S P EH R OW"},
    {"text":"spear", "phonemes":"S P IH R"},
    {"text":"specialist", "phonemes":"S P EH SH AH L IH S T"},
    {"text":"speedboat", "phonemes":"S P IY D B OW T"},
    {"text":"sphere", "phonemes":"S F IH R"},
    {"text":"sphynx", "phonemes":"S F IH NG K S"},
    {"text":"spider", "phonemes":"S P AY D ER"},
    {"text":"spike", "phonemes":"S P AY K"},
    {"text":"spinach", "phonemes":"S P IH N AH CH"},
    {"text":"spleen", "phonemes":"S P L IY N"},
    {"text":"sponge", "phonemes":"S P AH N JH"},
    {"text":"spoon", "phonemes":"S P UW N"},
    {"text":"spot", "phonemes":"S P AA T"},
    {"text":"spring", "phonemes":"S P R IH NG"},
    {"text":"sprout", "phonemes":"S P R AW T"},
    {"text":"spruce", "phonemes":"S P R UW S"},
    {"text":"spy", "phonemes":"S P AY"},
    {"text":"square", "phonemes":"S K W EH R"},
    {"text":"squash", "phonemes":"S K W AA SH"},
    {"text":"squid", "phonemes":"S K W IH D"},
    {"text":"squirrel", "phonemes":"S K W ER AH L"},
    {"text":"stage", "phonemes":"S T EY JH"},
    {"text":"staircase", "phonemes":"S T EH R K EY S"},
    {"text":"stamp", "phonemes":"S T AE M P"},
    {"text":"star", "phonemes":"S T AA R"},
    {"text":"start", "phonemes":"S T AA R T"},
    {"text":"starter", "phonemes":"S T AA R T ER"},
    {"text":"statistic", "phonemes":"S T AH T IH S T IH K"},
    {"text":"steam", "phonemes":"S T IY M"},
    {"text":"steel", "phonemes":"S T IY L"},
    {"text":"stem", "phonemes":"S T EH M"},
    {"text":"step", "phonemes":"S T EH P"},
    {"text":"step", "phonemes":"-BROTHER	S T EH P B R AH DH ER"},
    {"text":"step", "phonemes":"-DAUGHTER	S T EH P D AO T ER"},
    {"text":"step", "phonemes":"-FATHER	S T EH P F AA DH ER"},
    {"text":"step", "phonemes":"-GRANDFATHER	S T EH P G R AE N D F AA DH ER"},
    {"text":"step", "phonemes":"-GRANDMOTHER	S T EH P G R AE N D M AH DH ER"},
    {"text":"step", "phonemes":"-SISTER	S T EH P S IH S T ER"},
    {"text":"step", "phonemes":"-SON	S T EH P S AH N"},
    {"text":"step", "phonemes":"-UNCLE	S T EH P AH NG K AH L"},
    {"text":"stew", "phonemes":"S T UW"},
    {"text":"stick", "phonemes":"S T IH K"},
    {"text":"stinger", "phonemes":"S T IH NG ER"},
    {"text":"stitch", "phonemes":"S T IH CH"},
    {"text":"stock", "phonemes":"S T AA K"},
    {"text":"stocking", "phonemes":"S T AA K IH NG"},
    {"text":"stomach", "phonemes":"S T AH M AH K"},
    {"text":"stone", "phonemes":"S T OW N"},
    {"text":"stool", "phonemes":"S T UW L"},
    {"text":"stop", "phonemes":"S T AA P"},
    {"text":"stopsign", "phonemes":"S T AA P S AY N"},
    {"text":"stopwatch", "phonemes":"S T AA P W AA CH"},
    {"text":"store", "phonemes":"S T AO R"},
    {"text":"storm", "phonemes":"S T AO R M"},
    {"text":"stove", "phonemes":"S T OW V"},
    {"text":"stranger", "phonemes":"S T R EY N JH ER"},
    {"text":"straw", "phonemes":"S T R AO"},
    {"text":"stream", "phonemes":"S T R IY M"},
    {"text":"street", "phonemes":"S T R IY T"},
    {"text":"streetcar", "phonemes":"S T R IY T K AA R"},
    {"text":"stretch", "phonemes":"S T R EH CH"},
    {"text":"string", "phonemes":"S T R IH NG"},
    {"text":"structure", "phonemes":"S T R AH K CH ER"},
    {"text":"study", "phonemes":"S T AH D IY"},
    {"text":"sturgeon", "phonemes":"S T ER JH AH N"},
    {"text":"submarine", "phonemes":"S AH B M ER IY N"},
    {"text":"subway", "phonemes":"S AH B W EY"},
    {"text":"success", "phonemes":"S AH K S EH S"},
    {"text":"sudan", "phonemes":"S UW D AE N"},
    {"text":"suede", "phonemes":"S W EY D"},
    {"text":"sugar", "phonemes":"SH UH G ER"},
    {"text":"suggestion", "phonemes":"S AH JH EH S CH AH N"},
    {"text":"suit", "phonemes":"S UW T"},
    {"text":"summer", "phonemes":"S AH M ER"},
    {"text":"sun", "phonemes":"S AH N"},
    {"text":"sundial", "phonemes":"S AH N D AY L"},
    {"text":"sunflower", "phonemes":"S AH N F L AW ER"},
    {"text":"sunshine", "phonemes":"S AH N SH AY N"},
    {"text":"supermarket", "phonemes":"S UW P ER M AA R K IH T"},
    {"text":"supply", "phonemes":"S AH P L AY"},
    {"text":"support", "phonemes":"S AH P AO R T"},
    {"text":"surfboard", "phonemes":"S ER F B AO R D"},
    {"text":"surgeon", "phonemes":"S ER JH AH N"},
    {"text":"surname", "phonemes":"S ER N EY M"},
    {"text":"surprise", "phonemes":"S ER P R AY Z"},
    {"text":"sushi", "phonemes":"S UW SH IY"},
    {"text":"swallow", "phonemes":"S W AA L OW"},
    {"text":"swamp", "phonemes":"S W AA M P"},
    {"text":"swan", "phonemes":"S W AA N"},
    {"text":"sweater", "phonemes":"S W EH T ER"},
    {"text":"sweatshirt", "phonemes":"S W EH T SH ER T"},
    {"text":"sweatshop", "phonemes":"S W EH T SH AA P"},
    {"text":"swedish", "phonemes":"S W IY D IH SH"},
    {"text":"swim", "phonemes":"S W IH M"},
    {"text":"swing", "phonemes":"S W IH NG"},
    {"text":"swiss", "phonemes":"S W IH S"},
    {"text":"switch", "phonemes":"S W IH CH"},
    {"text":"sword", "phonemes":"S AO R D"},
    {"text":"swordfish", "phonemes":"S AO R D F IH SH"},
    {"text":"sycamore", "phonemes":"S IH K AH M AO R"},
    {"text":"syrup", "phonemes":"S ER AH P"},
    {"text":"system", "phonemes":"S IH S T AH M"},
    {"text":"table", "phonemes":"T EY B AH L"},
    {"text":"tablecloth", "phonemes":"T EY B AH L K L AO TH"},
    {"text":"tadpole", "phonemes":"T AE D P OW L"},
    {"text":"tail", "phonemes":"T EY L"},
    {"text":"tailor", "phonemes":"T EY L ER"},
    {"text":"talk", "phonemes":"T AO K"},
    {"text":"tank", "phonemes":"T AE NG K"},
    {"text":"tanker", "phonemes":"T AE NG K ER"},
    {"text":"target", "phonemes":"T AA R G AH T"},
    {"text":"taste", "phonemes":"T EY S T"},
    {"text":"taurus", "phonemes":"T AO R AH S"},
    {"text":"tax", "phonemes":"T AE K S"},
    {"text":"taxi", "phonemes":"T AE K S IY"},
    {"text":"taxicab", "phonemes":"T AE K S IY K AE B"},
    {"text":"tea", "phonemes":"T IY"},
    {"text":"teacher", "phonemes":"T IY CH ER"},
    {"text":"team", "phonemes":"T IY M"},
    {"text":"technician", "phonemes":"T EH K N IH SH AH N"},
    {"text":"teeth", "phonemes":"T IY TH"},
    {"text":"television", "phonemes":"T EH L AH V IH ZH AH N"},
    {"text":"teller", "phonemes":"T EH L ER"},
    {"text":"temper", "phonemes":"T EH M P ER"},
    {"text":"temperature", "phonemes":"T EH M P R AH CH ER"},
    {"text":"temple", "phonemes":"T EH M P AH L"},
    {"text":"tempo", "phonemes":"T EH M P OW"},
    {"text":"tendency", "phonemes":"T EH N D AH N S IY"},
    {"text":"tennis", "phonemes":"T EH N AH S"},
    {"text":"tenor", "phonemes":"T EH N ER"},
    {"text":"tent", "phonemes":"T EH N T"},
    {"text":"territory", "phonemes":"T EH R IH T AO R IY"},
    {"text":"textbook", "phonemes":"T EH K S T B UH K"},
    {"text":"texture", "phonemes":"T EH K S CH ER"},
    {"text":"theater", "phonemes":"TH IY EY T ER"},
    {"text":"theory", "phonemes":"TH IH R IY"},
    {"text":"thermometer", "phonemes":"TH ER M AA M AH T ER"},
    {"text":"thing", "phonemes":"TH IH NG"},
    {"text":"thistle", "phonemes":"TH IH S AH L"},
    {"text":"thread", "phonemes":"TH R EH D"},
    {"text":"thrill", "phonemes":"TH R IH L"},
    {"text":"throat", "phonemes":"TH R OW T"},
    {"text":"throne", "phonemes":"TH R OW N"},
    {"text":"thumb", "phonemes":"TH AH M"},
    {"text":"thunder", "phonemes":"TH AH N D ER"},
    {"text":"thunderstorm", "phonemes":"TH AH N D ER S T AO R M"},
    {"text":"ticket", "phonemes":"T IH K AH T"},
    {"text":"tie", "phonemes":"T AY"},
    {"text":"tiger", "phonemes":"T AY G ER"},
    {"text":"tile", "phonemes":"T AY L"},
    {"text":"time", "phonemes":"T AY M"},
    {"text":"timer", "phonemes":"T AY M ER"},
    {"text":"timpani", "phonemes":"T IH M P AH N IY"},
    {"text":"tin", "phonemes":"T IH N"},
    {"text":"tip", "phonemes":"T IH P"},
    {"text":"tire", "phonemes":"T AY ER"},
    {"text":"titanium", "phonemes":"T AY T EY N IY AH M"},
    {"text":"title", "phonemes":"T AY T AH L"},
    {"text":"toad", "phonemes":"T OW D"},
    {"text":"toast", "phonemes":"T OW S T"},
    {"text":"toe", "phonemes":"T OW"},
    {"text":"toenail", "phonemes":"T OW N EY L"},
    {"text":"toilet", "phonemes":"T OY L AH T"},
    {"text":"tomato", "phonemes":"T AH M EY T OW"},
    {"text":"tongue", "phonemes":"T AH NG"},
    {"text":"tooth", "phonemes":"T UW TH"},
    {"text":"toothbrush", "phonemes":"T UW TH B R AH SH"},
    {"text":"toothpaste", "phonemes":"T UW TH P EY S T"},
    {"text":"top", "phonemes":"T AA P"},
    {"text":"tornado", "phonemes":"T AO R N EY D OW"},
    {"text":"tortoise", "phonemes":"T AO R T AH S"},
    {"text":"touch", "phonemes":"T AH CH"},
    {"text":"tower", "phonemes":"T AW ER"},
    {"text":"town", "phonemes":"T AW N"},
    {"text":"toy", "phonemes":"T OY"},
    {"text":"tractor", "phonemes":"T R AE K T ER"},
    {"text":"trade", "phonemes":"T R EY D"},
    {"text":"traffic", "phonemes":"T R AE F IH K"},
    {"text":"trail", "phonemes":"T R EY L"},
    {"text":"train", "phonemes":"T R EY N"},
    {"text":"tramp", "phonemes":"T R AE M P"},
    {"text":"transaction", "phonemes":"T R AE N Z AE K SH AH N"},
    {"text":"transmission", "phonemes":"T R AE N S M IH SH AH N"},
    {"text":"transport", "phonemes":"T R AE N S P AO R T"},
    {"text":"trapezoid", "phonemes":"T R AE P AH Z OY D"},
    {"text":"tray", "phonemes":"T R EY"},
    {"text":"treatment", "phonemes":"T R IY T M AH N T"},
    {"text":"tree", "phonemes":"T R IY"},
    {"text":"trial", "phonemes":"T R AY AH L"},
    {"text":"triangle", "phonemes":"T R AY AE NG G AH L"},
    {"text":"trick", "phonemes":"T R IH K"},
    {"text":"trigonometry", "phonemes":"T R IH G AH N AH M EH T R IY"},
    {"text":"trip", "phonemes":"T R IH P"},
    {"text":"trombone", "phonemes":"T R AA M B OW N"},
    {"text":"trouble", "phonemes":"T R AH B AH L"},
    {"text":"trouser", "phonemes":"T R AW Z ER"},
    {"text":"trout", "phonemes":"T R AW T"},
    {"text":"trowel", "phonemes":"T R AW W EH L"},
    {"text":"truck", "phonemes":"T R AH K"},
    {"text":"trumpet", "phonemes":"T R AH M P AH T"},
    {"text":"trunk", "phonemes":"T R AH NG K"},
    {"text":"t", "phonemes":"-SHIRT	T IY S ER T"},
    {"text":"tsunami", "phonemes":"T S UW N AA M IY"},
    {"text":"tub", "phonemes":"T AH B"},
    {"text":"tuba", "phonemes":"T UW B AH"},
    {"text":"tugboat", "phonemes":"T AH G B OW T"},
    {"text":"tulip", "phonemes":"T UW L IH P"},
    {"text":"tuna", "phonemes":"T UW N AH"},
    {"text":"tune", "phonemes":"T UW N"},
    {"text":"turn", "phonemes":"T ER N"},
    {"text":"turnip", "phonemes":"T ER N AH P"},
    {"text":"turnover", "phonemes":"T ER N OW V ER"},
    {"text":"turret", "phonemes":"T ER AH T"},
    {"text":"turtle", "phonemes":"T ER T AH L"},
    {"text":"tv", "phonemes":"T IY V IY"},
    {"text":"twig", "phonemes":"T W IH G"},
    {"text":"twilight", "phonemes":"T W AY L AY T"},
    {"text":"twine", "phonemes":"T W AY N"},
    {"text":"twist", "phonemes":"T W IH S T"},
    {"text":"typhoon", "phonemes":"T AY F UW N"},
    {"text":"umbrella", "phonemes":"AH M B R EH L AH"},
    {"text":"uncle", "phonemes":"AH NG K AH L"},
    {"text":"undercloth", "phonemes":"AH N D ER K L AO TH"},
    {"text":"underpant", "phonemes":"AH N D ER P AE N T"},
    {"text":"undershirt", "phonemes":"AH N D ER SH ER T"},
    {"text":"underwear", "phonemes":"AH N D ER W EH R"},
    {"text":"utensil", "phonemes":"Y UW T EH N S AH L"},
    {"text":"vacation", "phonemes":"V EY K EY SH AH N"},
    {"text":"vacuum", "phonemes":"V AE K Y UW M"},
    {"text":"valley", "phonemes":"V AE L IY"},
    {"text":"van", "phonemes":"V AE N"},
    {"text":"vase", "phonemes":"V EY S"},
    {"text":"vault", "phonemes":"V AO L T"},
    {"text":"vegetable", "phonemes":"V EH JH T AH B AH L"},
    {"text":"vegetarian", "phonemes":"V EH JH AH T EH R IY AH N"},
    {"text":"veil", "phonemes":"V EY L"},
    {"text":"vein", "phonemes":"V EY N"},
    {"text":"velvet", "phonemes":"V EH L V AH T"},
    {"text":"verdict", "phonemes":"V ER D IH K T"},
    {"text":"vermicelli", "phonemes":"V AH R M AH S EH L IY"},
    {"text":"verse", "phonemes":"V ER S"},
    {"text":"vessel", "phonemes":"V EH S AH L"},
    {"text":"vest", "phonemes":"V EH S T"},
    {"text":"veterinarian", "phonemes":"V EH T R AH N EH R IY AH N"},
    {"text":"vibraphone", "phonemes":"V IH B R AH F OW N"},
    {"text":"vietnam", "phonemes":"V IY EH T N AA M"},
    {"text":"view", "phonemes":"V Y UW"},
    {"text":"vinyl", "phonemes":"V AY N AH L"},
    {"text":"viola", "phonemes":"V AY OW L AH"},
    {"text":"violet", "phonemes":"V AY AH L IH T"},
    {"text":"violin", "phonemes":"V AY AH L IH N"},
    {"text":"virgo", "phonemes":"V ER G OW"},
    {"text":"viscose", "phonemes":"V IH S OW Z"},
    {"text":"vise", "phonemes":"V AY S"},
    {"text":"vision", "phonemes":"V IH ZH AH N"},
    {"text":"visitor", "phonemes":"V IH Z IH T ER"},
    {"text":"voice", "phonemes":"V OY S"},
    {"text":"volcano", "phonemes":"V AA L K EY N OW"},
    {"text":"volleyball", "phonemes":"V AA L IY B AO L"},
    {"text":"voyage", "phonemes":"V OY AH JH"},
    {"text":"vulture", "phonemes":"V AH L CH ER"},
    {"text":"waiter", "phonemes":"W EY T ER"},
    {"text":"waitress", "phonemes":"W EY T R AH S"},
    {"text":"wall", "phonemes":"W AO L"},
    {"text":"wallaby", "phonemes":"W AA L AH B IY"},
    {"text":"wallet", "phonemes":"W AO L AH T"},
    {"text":"walrus", "phonemes":"W AO L R AH S"},
    {"text":"war", "phonemes":"W AO R"},
    {"text":"wash", "phonemes":"W AA SH"},
    {"text":"washer", "phonemes":"W AA SH ER"},
    {"text":"wasp", "phonemes":"W AA S P"},
    {"text":"waste", "phonemes":"W EY S T"},
    {"text":"watch", "phonemes":"W AA CH"},
    {"text":"watchmaker", "phonemes":"W AA CH M EY K ER"},
    {"text":"water", "phonemes":"W AO T ER"},
    {"text":"waterfall", "phonemes":"W AO T ER F AO L"},
    {"text":"wave", "phonemes":"W EY V"},
    {"text":"wax", "phonemes":"W AE K S"},
    {"text":"way", "phonemes":"W EY"},
    {"text":"wealth", "phonemes":"W EH L TH"},
    {"text":"weapon", "phonemes":"W EH P AH N"},
    {"text":"weasel", "phonemes":"W IY Z AH L"},
    {"text":"weather", "phonemes":"W EH DH ER"},
    {"text":"wedge", "phonemes":"W EH JH"},
    {"text":"wednesday", "phonemes":"W EH N Z D IY"},
    {"text":"weed", "phonemes":"W IY D"},
    {"text":"weeder", "phonemes":"W IY D ER"},
    {"text":"week", "phonemes":"W IY K"},
    {"text":"weight", "phonemes":"W EY T"},
    {"text":"whale", "phonemes":"W EY L"},
    {"text":"wheel", "phonemes":"W IY L"},
    {"text":"whip", "phonemes":"W IH P"},
    {"text":"whiskey", "phonemes":"W IH S K IY"},
    {"text":"whistle", "phonemes":"W IH S AH L"},
    {"text":"white", "phonemes":"W AY T"},
    {"text":"wholesaler", "phonemes":"HH OW L S EY L ER"},
    {"text":"whorl", "phonemes":"W ER L"},
    {"text":"wilderness", "phonemes":"W IH L D ER N AH S"},
    {"text":"william", "phonemes":"W IH L Y AH M"},
    {"text":"willow", "phonemes":"W IH L OW"},
    {"text":"wind", "phonemes":"W AY N D"},
    {"text":"window", "phonemes":"W IH N D OW"},
    {"text":"wine", "phonemes":"W AY N"},
    {"text":"wing", "phonemes":"W IH NG"},
    {"text":"winter", "phonemes":"W IH N T ER"},
    {"text":"wire", "phonemes":"W AY ER"},
    {"text":"wish", "phonemes":"W IH SH"},
    {"text":"witch", "phonemes":"W IH CH"},
    {"text":"withdrawal", "phonemes":"W IH DH D R AO AH L"},
    {"text":"witness", "phonemes":"W IH T N AH S"},
    {"text":"wolf", "phonemes":"W UH L F"},
    {"text":"wood", "phonemes":"W UH D"},
    {"text":"wool", "phonemes":"W UH L"},
    {"text":"woolen", "phonemes":"W UH L AH N"},
    {"text":"word", "phonemes":"W ER D"},
    {"text":"work", "phonemes":"W ER K"},
    {"text":"workshop", "phonemes":"W ER K SH AA P"},
    {"text":"worm", "phonemes":"W ER M"},
    {"text":"wound", "phonemes":"W AW N D"},
    {"text":"wound", "phonemes":"W UW N D"},
    {"text":"wrecker", "phonemes":"R EH K ER"},
    {"text":"wren", "phonemes":"R EH N"},
    {"text":"wrench", "phonemes":"R EH N CH"},
    {"text":"wrinkle", "phonemes":"R IH NG K AH L"},
    {"text":"wrist", "phonemes":"R IH S T"},
    {"text":"writer", "phonemes":"R AY T ER"},
    {"text":"xylophone", "phonemes":"Z AY L AH F OW N"},
    {"text":"yacht", "phonemes":"Y AA T"},
    {"text":"yak", "phonemes":"Y AE K"},
    {"text":"yam", "phonemes":"Y AE M"},
    {"text":"yard", "phonemes":"Y AA R D"},
    {"text":"yarn", "phonemes":"Y AA R N"},
    {"text":"year", "phonemes":"Y IH R"},
    {"text":"yellow", "phonemes":"Y EH L OW"},
    {"text":"yew", "phonemes":"Y UW"},
    {"text":"yogurt", "phonemes":"Y OW G ER T"},
    {"text":"yoke", "phonemes":"Y OW K"},
    {"text":"zebra", "phonemes":"Z IY B R AH"},
    {"text":"zephyr", "phonemes":"Z EH F ER"},
    {"text":"zinc", "phonemes":"Z IH NG K"},
    {"text":"zipper", "phonemes":"Z IH P ER"},
    {"text":"zoo", "phonemes":"Z UW"},
];
